Repository microsoft/kiota, pull requests merged in 2021-08, with the labels that each got.

#445 bugfix/Typescript removed extra collection map
  serialization/typescript/json/src/jsonParseNode.ts
Labels: bug

#330 adds support for http middlewares
  CHANGELOG.md
  abstractions/dotnet/src/IMiddlewareOption.cs
  abstractions/dotnet/src/Microsoft.Kiota.Abstractions.csproj
  abstractions/dotnet/src/RequestInfo.cs
  abstractions/java/lib/build.gradle
  abstractions/java/lib/src/main/java/com/microsoft/kiota/MiddlewareOption.java
  abstractions/java/lib/src/main/java/com/microsoft/kiota/RequestInfo.java
  abstractions/typescript/package-lock.json
  abstractions/typescript/package.json
  abstractions/typescript/src/index.ts
  abstractions/typescript/src/middlewareOption.ts
  abstractions/typescript/src/requestInfo.ts
  http/dotnet/httpclient/src/HttpClientBuilder.cs
  http/dotnet/httpclient/src/HttpCore.cs
  http/dotnet/httpclient/src/Microsoft.Kiota.Http.HttpClient.csproj
  http/java/okhttp/lib/build.gradle
  http/java/okhttp/lib/src/main/java/com/microsoft/kiota/http/HttpCore.java
  http/java/okhttp/lib/src/main/java/com/microsoft/kiota/http/OkHttpClientBuilder.java
  http/typescript/fetch/package-lock.json
  http/typescript/fetch/package.json
  http/typescript/fetch/src/httpClient.ts
  http/typescript/fetch/src/httpCore.ts
  http/typescript/fetch/src/index.ts
  http/typescript/fetch/src/middleware.ts
  src/Kiota.Builder/CodeDOM/CodeMethod.cs
  src/Kiota.Builder/CodeDOM/CodeParameter.cs
  src/Kiota.Builder/KiotaBuilder.cs
  src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
  src/Kiota.Builder/Refiners/JavaRefiner.cs
  src/Kiota.Builder/Refiners/TypeScriptRefiner.cs
  src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs
  tests/Kiota.Builder.Tests/Refiners/JavaLanguageRefinerTests.cs
  tests/Kiota.Builder.Tests/Refiners/TypeScriptLanguageRefinerTests.cs
  tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Java/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/TypeScript/CodeMethodWriterTests.cs
Labels: generator

#471 bugfix/ruby-serialization-workflow-deployStage
  .github/workflows/serialization-ruby-json.yml
Labels: Ruby

#493 - updates package lock for release
  http/typescript/fetch/package-lock.json
  serialization/typescript/json/package-lock.json
Labels: TypeScript

#494 Adds support for package validation on dotnet build
  abstractions/dotnet/src/Microsoft.Kiota.Abstractions.csproj
  authentication/dotnet/azure/src/Microsoft.Kiota.Authentication.Azure.csproj
  http/dotnet/httpclient/src/Microsoft.Kiota.Http.HttpClient.csproj
  serialization/dotnet/json/src/Microsoft.Kiota.Serialization.Json.csproj
Labels: CSharp

#496 - fixes a workflow issue where ruby http would be published with no token and fail
  .github/workflows/http-ruby-nethttp.yml
Labels: Ruby

#495 - udpates documentation to indicate required parameters
  docs/index.md
  docs/odata.md
Labels: documentation

#500 Add doc comments for HttpClient project for dotnet
  http/dotnet/httpclient/.editorconfig
  http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.sln
  http/dotnet/httpclient/README.md
  http/dotnet/httpclient/src/HttpClientBuilder.cs
  http/dotnet/httpclient/src/HttpCore.cs
  http/dotnet/httpclient/src/Microsoft.Kiota.Http.HttpClient.csproj
Labels: CSharp, Cosmetic

#501 Add doc comments for Serialization project for dotnet
  serialization/dotnet/json/.editorconfig
  serialization/dotnet/json/Microsoft.Kiota.Serialization.Json.sln
  serialization/dotnet/json/README.md
  serialization/dotnet/json/src/JsonParseNode.cs
  serialization/dotnet/json/src/JsonParseNodeFactory.cs
  serialization/dotnet/json/src/JsonSerializationWriter.cs
  serialization/dotnet/json/src/JsonSerializationWriterFactory.cs
  serialization/dotnet/json/src/Microsoft.Kiota.Serialization.Json.csproj
Labels: CSharp, Cosmetic

#502 Adding double mapping to TS conversion
  src/Kiota.Builder/Writers/TypeScript/TypeScriptConventionService.cs
Labels: TypeScript

#513 Adds docs comments for the Abstractions project for dotnet
  abstractions/dotnet/.editorconfig
  abstractions/dotnet/Microsoft.Kiota.Abstractions.sln
  abstractions/dotnet/README.md
  abstractions/dotnet/src/ApiClientBuilder.cs
  abstractions/dotnet/src/HttpMethod.cs
  abstractions/dotnet/src/IHttpCore.cs
  abstractions/dotnet/src/IMiddlewareOption.cs
  abstractions/dotnet/src/IResponseHandler.cs
  abstractions/dotnet/src/Microsoft.Kiota.Abstractions.csproj
  abstractions/dotnet/src/NativeResponseHandler.cs
  abstractions/dotnet/src/NativeResponseWrapper.cs
  abstractions/dotnet/src/QueryParametersBase.cs
  abstractions/dotnet/src/RequestInfo.cs
  abstractions/dotnet/src/authentication/AnonymousAuthenticationProvider.cs
  abstractions/dotnet/src/authentication/BaseBearerTokenAuthenticationProvider.cs
  abstractions/dotnet/src/authentication/IAuthenticationProvider.cs
  abstractions/dotnet/src/extensions/StringExtensions.cs
  abstractions/dotnet/src/serialization/IParsable.cs
  abstractions/dotnet/src/serialization/IParseNode.cs
  abstractions/dotnet/src/serialization/IParseNodeFactory.cs
  abstractions/dotnet/src/serialization/ISerializationWriter.cs
  abstractions/dotnet/src/serialization/ISerializationWriterFactory.cs
  abstractions/dotnet/src/serialization/ParseNodeFactoryRegistry.cs
  abstractions/dotnet/src/serialization/ParseNodeProxyFactory.cs
  abstractions/dotnet/src/serialization/SerializationWriterFactoryRegistry.cs
  abstractions/dotnet/src/serialization/SerializationWriterProxyFactory.cs
  abstractions/dotnet/src/store/BackingStoreFactorySingleton.cs
  abstractions/dotnet/src/store/BackingStoreParseNodeFactory.cs
  abstractions/dotnet/src/store/BackingStoreSerializationWriterProxyFactory.cs
  abstractions/dotnet/src/store/IBackedModel.cs
  abstractions/dotnet/src/store/IBackingStore.cs
  abstractions/dotnet/src/store/IBackingStoreFactory.cs
  abstractions/dotnet/src/store/InMemoryBackingStore.cs
  abstractions/dotnet/src/store/InMemoryBackingStoreFactory.cs
Labels: CSharp, Cosmetic

#512 Add doc comments for Authentication project for dotnet
  authentication/dotnet/azure/.editorconfig
  authentication/dotnet/azure/Microsoft.Kiota.Authentication.Azure.sln
  authentication/dotnet/azure/README.md
  authentication/dotnet/azure/src/AzureIdentityAuthenticationProvider.cs
  authentication/dotnet/azure/src/Microsoft.Kiota.Authentication.Azure.csproj
Labels: CSharp, Cosmetic

#522 Add test project for HttpClient project for dotnet
  .github/workflows/http-dotnet-httpclient.yml
  http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.Tests/HttpClientBuilderTests.cs
  http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.Tests/HttpCoreTests.cs
  http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.Tests/Microsoft.Kiota.Http.HttpClient.Tests.csproj
  http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.Tests/Mocks/TestHttpMessageHandler.cs
  http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.sln
  http/dotnet/httpclient/README.md
  http/dotnet/httpclient/src/HttpClientBuilder.cs
  http/dotnet/httpclient/src/HttpCore.cs
Labels: CSharp

#523 Adds test project for Authentication project for dotnet
  .github/workflows/authentication-dotnet-azure.yml
  authentication/dotnet/azure/Microsoft.Kiota.Authentication.Azure.Tests/AzureIdentityAuthenticationProviderTests.cs
  authentication/dotnet/azure/Microsoft.Kiota.Authentication.Azure.Tests/Microsoft.Kiota.Authentication.Azure.Tests.csproj
  authentication/dotnet/azure/Microsoft.Kiota.Authentication.Azure.sln
  authentication/dotnet/azure/README.md
Labels: CSharp

#520 Adds Docker run example for a TypeScript SDK
  generator/docker.md
Labels: documentation, generator

#525 adds options support for native response handlers
  abstractions/dotnet/src/NativeResponseWrapper.cs
  abstractions/java/lib/src/main/java/com/microsoft/kiota/NativeResponseWrapper.java
  abstractions/java/lib/src/main/java/com/microsoft/kiota/PentaFunction.java
  abstractions/java/lib/src/main/java/com/microsoft/kiota/TriFunction.java
  abstractions/typescript/src/nativeResponseWrapper.ts
Labels: CSharp, TypeScript, Java

#529 Adds test project for Serialization project
  .github/workflows/serialization-dotnet-json.yml
  serialization/dotnet/json/Microsoft.Kiota.Serialization.Json.Tests/JsonParseNodeFactoryTests.cs
  serialization/dotnet/json/Microsoft.Kiota.Serialization.Json.Tests/JsonParseNodeTests.cs
  serialization/dotnet/json/Microsoft.Kiota.Serialization.Json.Tests/JsonSerializationWriterFactoryTests.cs
  serialization/dotnet/json/Microsoft.Kiota.Serialization.Json.Tests/JsonSerializationWriterTests.cs
  serialization/dotnet/json/Microsoft.Kiota.Serialization.Json.Tests/Microsoft.Kiota.Serialization.Json.Tests.csproj
  serialization/dotnet/json/Microsoft.Kiota.Serialization.Json.Tests/Mocks/TestEntity.cs
  serialization/dotnet/json/Microsoft.Kiota.Serialization.Json.sln
  serialization/dotnet/json/README.md
  serialization/dotnet/json/src/JsonParseNode.cs
  serialization/dotnet/json/src/JsonSerializationWriter.cs
  serialization/java/json/lib/src/main/java/com/microsoft/kiota/serialization/JsonSerializationWriter.java
Labels: CSharp

#557 Adds test project for Abstraction project for dotnet
  .github/workflows/abstractions-dotnet.yml
  abstractions/dotnet/Microsoft.Kiota.Abstractions.Tests/Authentication/AuthenticationTests.cs
  abstractions/dotnet/Microsoft.Kiota.Abstractions.Tests/Microsoft.Kiota.Abstractions.Tests.csproj
  abstractions/dotnet/Microsoft.Kiota.Abstractions.Tests/RequestInfoTests.cs
  abstractions/dotnet/Microsoft.Kiota.Abstractions.Tests/Serialization/ParseNodeFactoryRegistryTests.cs
  abstractions/dotnet/Microsoft.Kiota.Abstractions.Tests/Serialization/SerializationWriterFactoryRegistryTests.cs
  abstractions/dotnet/Microsoft.Kiota.Abstractions.Tests/Store/InMemoryBackingStoreTests.cs
  abstractions/dotnet/Microsoft.Kiota.Abstractions.sln
  abstractions/dotnet/README.md
  abstractions/dotnet/src/RequestInfo.cs
Labels: CSharp

#558 multiple minor fixes from snippets generation and documentation writing
  CHANGELOG.md
  README.md
  src/Kiota.Builder/CodeDOM/CodeNamespace.cs
  src/Kiota.Builder/Extensions/OpenApiSchemaExtensions.cs
  src/Kiota.Builder/Extensions/OpenApiUrlTreeNodeExtensions.cs
  src/Kiota.Builder/GenerationConfiguration.cs
  src/Kiota.Builder/KiotaBuilder.cs
  src/Kiota.Builder/Writers/CSharp/CSharpConventionService.cs
  src/kiota/KiotaHost.cs
  tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Labels: generator

#569 - updates package locks for publishing
  authentication/typescript/azure/package-lock.json
  http/typescript/fetch/package-lock.json
Labels: TypeScript

#570 - fixes a reference issue after request info rename
  abstractions/dotnet/Microsoft.Kiota.Abstractions.Tests/RequestInformationTests.cs
Labels: CSharp

#571 - fixes request information reference after rename
  abstractions/dotnet/Microsoft.Kiota.Abstractions.Tests/Authentication/AuthenticationTests.cs
Labels: CSharp
