Repository microsoft/kiota, pull requests merged in 2021-12, with the labels that each got.

#910 Go reserved keywords fix and nil check fix
  CHANGELOG.md
  src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
  src/Kiota.Builder/Refiners/GoRefiner.cs
  src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
  tests/Kiota.Builder.Tests/Refiners/GoLanguageRefinerTests.cs
Labels: Go

#664 PHP Generation
  CHANGELOG.md
  README.md
  src/Kiota.Builder/Extensions/StringExtensions.cs
  src/Kiota.Builder/PathSegmenters/PHPPathSegmenter.cs
  src/Kiota.Builder/Refiners/CSharpRefiner.cs
  src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
  src/Kiota.Builder/Refiners/ILanguageRefiner.cs
  src/Kiota.Builder/Refiners/JavaRefiner.cs
  src/Kiota.Builder/Refiners/PhpRefiner.cs
  src/Kiota.Builder/Refiners/PhpReservedNamesProvider.cs
  src/Kiota.Builder/Refiners/RubyRefiner.cs
  src/Kiota.Builder/Refiners/TypeScriptRefiner.cs
  src/Kiota.Builder/Writers/LanguageWriter.cs
  src/Kiota.Builder/Writers/Php/CodeClassDeclarationWriter.cs
  src/Kiota.Builder/Writers/Php/CodeClassEndWriter.cs
  src/Kiota.Builder/Writers/Php/CodeEnumWriter.cs
  src/Kiota.Builder/Writers/Php/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Php/CodePropertyWriter.cs
  src/Kiota.Builder/Writers/Php/PhpConventionService.cs
  src/Kiota.Builder/Writers/Php/PhpWriter.cs
  tests/Kiota.Builder.IntegrationTests/GenerateSample.cs
  tests/Kiota.Builder.Tests/Refiners/PhpLanguageRefinerTests.cs
  tests/Kiota.Builder.Tests/Refiners/RubyLanguageRefinerTests.cs
  tests/Kiota.Builder.Tests/Writers/LanguageWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Php/CodeClassDeclarationWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Php/CodeClassEndWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Php/CodeEnumWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Php/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Php/CodePropertyWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Php/PhpWriterTests.cs
Labels: PHP

#912 fixes a bug where reserved keyword replacement in go would miss some cases
  src/Kiota.Builder/Refiners/GoRefiner.cs
  tests/Kiota.Builder.Tests/Refiners/GoLanguageRefinerTests.cs
Labels: Go

#919 - Fixes a bug in Go where empty collections would not be serialized
  CHANGELOG.md
  serialization/go/json/json_serialization_writer.go
Labels: Go

#917 Fixes a bug where OData select query parameter would not be normalized
  CHANGELOG.md
  abstractions/go/request_information.go
Labels: Go

#926 Fixes a bug where Java and Go escaped model properties would not serialize properly
  CHANGELOG.md
  src/Kiota.Builder/CodeDOM/CodeProperty.cs
  src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
  src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Java/CodeClassDeclarationWriter.cs
  src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
  tests/Kiota.Builder.Tests/Refiners/GoLanguageRefinerTests.cs
  tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Java/CodeMethodWriterTests.cs
Labels: Go, Java

#931 - fixes a bug where generation would fail because of empty usings
  CHANGELOG.md
  src/Kiota.Builder/Refiners/CSharpRefiner.cs
  src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
Labels: CSharp, TypeScript, Java
