Repository microsoft/kiota, pull requests merged in 2021-09, with the labels that each got.

#595 - fixes multiple broken links and typos in the documentation
  README.md
  docs/generator/build.md
  docs/generator/tool.md
Labels: documentation

#589 Add redirect,retry and compression handlers to HttpClient library for dotnet
  http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.Tests/Extensions/HttpRequestMessageExtensionsTests.cs
  http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.Tests/Middleware/CompressionHandlerTests.cs
  http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.Tests/Middleware/RedirectHandlerTests.cs
  http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.Tests/Middleware/RetryHandlerTests.cs
  http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.Tests/Mocks/MockCompressedContent.cs
  http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.Tests/Mocks/MockRedirectHandler.cs
  http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.Tests/Mocks/TestHttpMessageHandler.cs
  http/dotnet/httpclient/src/Extensions/HttpRequestMessageExtensions.cs
  http/dotnet/httpclient/src/HttpClientBuilder.cs
  http/dotnet/httpclient/src/HttpCore.cs
  http/dotnet/httpclient/src/Middleware/CompressionHandler.cs
  http/dotnet/httpclient/src/Middleware/Options/RedirectHandlerOption.cs
  http/dotnet/httpclient/src/Middleware/Options/RetryHandlerOption.cs
  http/dotnet/httpclient/src/Middleware/RedirectHandler.cs
  http/dotnet/httpclient/src/Middleware/RetryHandler.cs
  http/dotnet/httpclient/src/Properties/AssemblyInfo.cs
Labels: CSharp

#599 Setup final handler for default httpClient
  http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.Tests/HttpClientBuilderTests.cs
  http/dotnet/httpclient/src/HttpClientBuilder.cs
  http/dotnet/httpclient/src/HttpCore.cs
  http/java/okhttp/lib/src/main/java/com/microsoft/kiota/http/HttpCore.java
  http/java/okhttp/lib/src/main/java/com/microsoft/kiota/http/OkHttpClientBuilder.java
Labels: CSharp

#609 Add Chaos and Telemetry Handlers
  http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.Tests/Middleware/ChaosHandlerTests.cs
  http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.Tests/Middleware/TelemetryHandlerTests.cs
  http/dotnet/httpclient/src/Middleware/ChaosHandler.cs
  http/dotnet/httpclient/src/Middleware/Options/ChaosHandlerOption.cs
  http/dotnet/httpclient/src/Middleware/Options/TelemetryHandlerOption.cs
  http/dotnet/httpclient/src/Middleware/TelemetryHandler.cs
Labels: CSharp

#621 Fixes broken links in required tools docs
  docs/requiredtools/dotnet.md
  docs/requiredtools/go.md
  docs/requiredtools/java.md
  docs/requiredtools/ruby.md
  docs/requiredtools/typescript.md
Labels: documentation, Cosmetic

#580 - improves introduction to generating SDK
  README.md
  docs/requiredtools/dotnet.md
Labels: documentation, generator

#626 - fixes #622 a bug where root URL would not be parsed from the document
  CHANGELOG.md
  src/Kiota.Builder/GenerationConfiguration.cs
  src/Kiota.Builder/KiotaBuilder.cs
  tests/Kiota.Builder.IntegrationTests/ToDoApi.yaml
  tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Labels: generator

#627 Fix for query parameter building in dotnet
  abstractions/dotnet/Microsoft.Kiota.Abstractions.Tests/QueryParametersBaseTests.cs
  abstractions/dotnet/src/QueryParametersBase.cs
  http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.Tests/HttpCoreTests.cs
  http/dotnet/httpclient/src/HttpCore.cs
Labels: CSharp

#638 [Retry Handler] Respect retry-after: <date> in dotnet
  http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.Tests/Middleware/RetryHandlerTests.cs
  http/dotnet/httpclient/src/Middleware/RetryHandler.cs
Labels: CSharp

#654 - upgrade gradle wrapper to latest
  abstractions/java/gradle/wrapper/gradle-wrapper.properties
  abstractions/java/gradlew
  authentication/java/azure/gradle/wrapper/gradle-wrapper.properties
  authentication/java/azure/gradlew
  http/java/okhttp/gradle/wrapper/gradle-wrapper.properties
  http/java/okhttp/gradlew
  serialization/java/json/gradle/wrapper/gradle-wrapper.properties
  serialization/java/json/gradlew
Labels: Java

#657 Filter CodeElement type during replacement of reserved names
  src/Kiota.Builder/Refiners/CSharpRefiner.cs
  src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
  tests/Kiota.Builder.Tests/Refiners/CSharpLanguageRefinerTests.cs
Labels: CSharp

#655 Feature/codespace
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: generator
