Repository microsoft/kiota, pull requests merged in 2021-11, with the labels that each got.

#778 - bumps generator version number
  CHANGELOG.md
  src/kiota/kiota.csproj
Labels: Go

#779 - fixes indirect declarations for go abstractions
  abstractions/go/go.mod
Labels: Go

#780 - udpate go mod references for core libs
  authentication/go/azure/go.mod
  authentication/go/azure/go.sum
  http/go/nethttp/go.mod
  http/go/nethttp/go.sum
  serialization/go/json/go.mod
  serialization/go/json/go.sum
Labels: Go

#781 - generator version bump
  CHANGELOG.md
  src/kiota/kiota.csproj
Labels: Go

#782 hotfix/go auth mod name
  README.md
  authentication/go/azure/go.mod
Labels: Go

#777 fixes a bug where collections of enums would not be mapped properly
  CHANGELOG.md
  src/Kiota.Builder/KiotaBuilder.cs
Labels: generator

#789 go scalar collections deserialization
  CHANGELOG.md
  src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
Labels: Go

#795 adds support for base url
  CHANGELOG.md
  abstractions/dotnet/src/IRequestAdapter.cs
  abstractions/dotnet/src/Microsoft.Kiota.Abstractions.csproj
  abstractions/go/request_adapter.go
  abstractions/java/lib/build.gradle
  abstractions/java/lib/src/main/java/com/microsoft/kiota/RequestAdapter.java
  abstractions/ruby/microsoft_kiota_abstractions/lib/microsoft_kiota_abstractions/request_adapter.rb
  abstractions/ruby/microsoft_kiota_abstractions/lib/microsoft_kiota_abstractions/version.rb
  abstractions/typescript/package-lock.json
  abstractions/typescript/package.json
  abstractions/typescript/src/requestAdapter.ts
  http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClientLibrary.Tests/Extensions/HttpRequestMessageExtensionsTests.cs
  http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClientLibrary.Tests/Middleware/TelemetryHandlerTests.cs
  http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClientLibrary.Tests/RequestAdapterTests.cs
  http/dotnet/httpclient/src/HttpClientRequestAdapter.cs
  http/dotnet/httpclient/src/Microsoft.Kiota.Http.HttpClientLibrary.csproj
  http/go/nethttp/go.mod
  http/go/nethttp/nethttp_request_adapter.go
  http/java/okhttp/lib/build.gradle
  http/java/okhttp/lib/src/main/java/com/microsoft/kiota/http/OkHttpRequestAdapter.java
  http/ruby/nethttp/microsoft_kiota_nethttplibrary/Gemfile
  http/ruby/nethttp/microsoft_kiota_nethttplibrary/lib/microsoft_kiota_nethttplibrary/net_http_request_adapter.rb
  http/ruby/nethttp/microsoft_kiota_nethttplibrary/lib/microsoft_kiota_nethttplibrary/version.rb
  http/typescript/fetch/package-lock.json
  http/typescript/fetch/package.json
  http/typescript/fetch/src/fetchRequestAdapter.ts
  src/Kiota.Builder/CodeDOM/CodeMethod.cs
  src/Kiota.Builder/Extensions/OpenApiUrlTreeNodeExtensions.cs
  src/Kiota.Builder/KiotaBuilder.cs
  src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Ruby/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs
Labels: generator

#811 - udpates package lock for release
  http/typescript/fetch/package-lock.json
Labels: TypeScript

#812 Use queryParameters on setQueryStringParametersFromRawObject
  CHANGELOG.md
  abstractions/typescript/package-lock.json
  abstractions/typescript/package.json
  abstractions/typescript/src/requestInformation.ts
Labels: TypeScript

#814 - updates reference to go abstractions
  http/go/nethttp/go.mod
  http/go/nethttp/go.sum
Labels: Go

#815 upgrades kiota to dotnet 6
  .devcontainer/Dockerfile
  .github/workflows/abstractions-dotnet.yml
  .github/workflows/authentication-dotnet-azure.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/create-release.yml
  .github/workflows/dotnet-tool.yml
  .github/workflows/dotnet.yml
  .github/workflows/http-dotnet-httpclient.yml
  .github/workflows/serialization-dotnet-json.yml
  .github/workflows/sonarcloud.yml
  .vscode/launch.json
  CHANGELOG.md
  Dockerfile
  abstractions/dotnet/Microsoft.Kiota.Abstractions.Tests/Microsoft.Kiota.Abstractions.Tests.csproj
  authentication/dotnet/azure/Microsoft.Kiota.Authentication.Azure.Tests/Microsoft.Kiota.Authentication.Azure.Tests.csproj
  docs/generator/build.md
  docs/requiredtools/dotnet.md
  docs/requiredtools/kiota.md
  http/README.md
  http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClientLibrary.Tests/Microsoft.Kiota.Http.HttpClientLibrary.Tests.csproj
  serialization/README.md
  serialization/dotnet/json/Microsoft.Kiota.Serialization.Json.Tests/Microsoft.Kiota.Serialization.Json.Tests.csproj
  src/Kiota.Builder/Kiota.Builder.csproj
  src/Kiota.Builder/KiotaBuilder.cs
  src/kiota/kiota.csproj
  tests/Kiota.Builder.IntegrationTests/Kiota.Builder.IntegrationTests.csproj
  tests/Kiota.Builder.Tests/Kiota.Builder.Tests.csproj
  tests/Kiota.Tests/Kiota.Tests.csproj
Labels: generator

#823 fixes json deserialization for go
  CHANGELOG.md
  serialization/go/json/json_parse_node.go
  src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
Labels: Go

#829 fixes a bug where query parameters would not be added to the request in go
  CHANGELOG.md
  abstractions/go/go.mod
  abstractions/go/go.sum
  abstractions/go/query_parameters_base.go
  abstractions/go/request_information.go
  abstractions/go/request_information_test.go
  src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
  src/Kiota.Builder/Refiners/GoRefiner.cs
  src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
  tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
Labels: Go

#840 - updates package reference after abstractions update in go
  http/go/nethttp/go.mod
  http/go/nethttp/go.sum
Labels: Go

#831 - fixes a bug where at signs in path would derail generation
  CHANGELOG.md
  src/Kiota.Builder/Extensions/OpenApiUrlTreeNodeExtensions.cs
  tests/Kiota.Builder.Tests/Extensions/OpenApiUrlTreeNodeExtensionsTests.cs
Labels: generator

#843 - fixes a bug where query parameters would be missing in go
  abstractions/go/request_information.go
  src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
  tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
Labels: Go

#842 bugfix: inherited properties would be missing inheritance information
  src/Kiota.Builder/Extensions/OpenApiSchemaExtensions.cs
  src/Kiota.Builder/KiotaBuilder.cs
  tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Labels: generator

#845 aligns doc comments for generation and core packages
  CHANGELOG.md
  authentication/go/azure/azure_identity_authentication_provider.go
  http/go/nethttp/kiota_client_factory.go
  http/go/nethttp/middleware.go
  http/go/nethttp/nethttp_request_adapter.go
  http/go/nethttp/pipeline.go
  http/go/nethttp/redirect_handler.go
  http/go/nethttp/retry_handler.go
  serialization/go/json/json_parse_node.go
  serialization/go/json/json_parse_node_factory.go
  serialization/go/json/json_serialization_writer.go
  serialization/go/json/json_serialization_writer_factory.go
  src/Kiota.Builder/Writers/Go/CodeClassDeclarationWriter.cs
  src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
  tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
Labels: Go

#850 Fixes a bug where HttpContent headers failed to be added to the request in dotnet.
  CHANGELOG.md
  http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClientLibrary.Tests/RequestAdapterTests.cs
  http/dotnet/httpclient/src/HttpClientRequestAdapter.cs
  http/dotnet/httpclient/src/Microsoft.Kiota.Http.HttpClientLibrary.csproj
Labels: CSharp

#846 additional concepts documentation
  docs/experience.md
  docs/extending/authentication.md
  docs/extending/kiotaabstractions.md
  docs/extending/models.md
  docs/extending/requestbuilders.md
  docs/extending/serialization.md
  docs/odata.md
  docs/requiredtools/dotnet.md
Labels: documentation, generator

#874 [Abstractions] Add CancellationToken parameter in send methods in dotnet
  abstractions/dotnet/Microsoft.Kiota.Abstractions.Tests/Serialization/ParseNodeFactoryRegistryTests.cs
  abstractions/dotnet/src/IRequestAdapter.cs
  abstractions/dotnet/src/Microsoft.Kiota.Abstractions.csproj
  http/dotnet/httpclient/src/HttpClientRequestAdapter.cs
  http/dotnet/httpclient/src/Microsoft.Kiota.Http.HttpClientLibrary.csproj
  src/Kiota.Builder/CodeDOM/CodeParameter.cs
  src/Kiota.Builder/KiotaBuilder.cs
  src/Kiota.Builder/Refiners/CSharpRefiner.cs
  src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
  src/Kiota.Builder/Refiners/GoRefiner.cs
  src/Kiota.Builder/Refiners/JavaRefiner.cs
  src/Kiota.Builder/Refiners/RubyRefiner.cs
  src/Kiota.Builder/Refiners/TypeScriptRefiner.cs
  src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
  tests/Kiota.Builder.Tests/Refiners/CSharpLanguageRefinerTests.cs
  tests/Kiota.Builder.Tests/Refiners/GoLanguageRefinerTests.cs
  tests/Kiota.Builder.Tests/Refiners/JavaLanguageRefinerTests.cs
  tests/Kiota.Builder.Tests/Refiners/RubyLanguageRefinerTests.cs
  tests/Kiota.Builder.Tests/Refiners/TypeScriptLanguageRefinerTests.cs
  tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs
Labels: CSharp

#877 fixes a casing issue with go doc comments
  src/Kiota.Builder/Writers/Go/CodeClassDeclarationWriter.cs
Labels: Go

#892 - fixes a bug where default scopes initialization would fail for go azure identity provider
  authentication/go/azure/azure_identity_authentication_provider.go
Labels: Go

#898 - adds automation for issues tagged with CLI
  .github/workflows/issue-labels-projects.yml
Labels: CLI

#899 aligns go lib version accross libraries
  .github/workflows/abstractions-go.yml
  .github/workflows/authentication-go-azure.yml
  .github/workflows/http-go-nethttp.yml
  .github/workflows/serialization-go-json.yml
  CHANGELOG.md
  abstractions/go/go.mod
  abstractions/go/go.sum
  authentication/go/azure/go.mod
  authentication/go/azure/go.sum
  http/go/nethttp/go.mod
  http/go/nethttp/go.sum
  serialization/go/json/go.mod
  serialization/go/json/go.sum
Labels: Go
