Repository microsoft/kiota, pull requests merged in 2022-05, with the labels that each got.

#1537 - fixes a bug in the go overloads generation
  CHANGELOG.md
  src/Kiota.Builder/Refiners/GoRefiner.cs
  tests/Kiota.Builder.Tests/Refiners/GoLanguageRefinerTests.cs
Labels: Go

#1540 - fixes a bug where inherited names would not be replaced
  CHANGELOG.md
  src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
Labels: Go

#1545 - removes a workflow that was missed during the last PR
  .github/workflows/dotnet-tool.yml
Labels: generator

#1555 - bumps version number to trigger automated release for docker
  CHANGELOG.md
  src/kiota/kiota.csproj
Labels: generator

#1548 Revise command-line interface
  .vscode/launch.json
  CHANGELOG.md
  Dockerfile
  docs/using.md
  src/kiota/KiotaHost.cs
  src/kiota/kiota.csproj
Labels: generator

#1546 PHP: Add plain text support
  .github/workflows/serialization-php-text.yml
  CHANGELOG.md
  serialization/php/text/.editorconfig
  serialization/php/text/.gitattributes
  serialization/php/text/.gitignore
  serialization/php/text/README.md
  serialization/php/text/composer.json
  serialization/php/text/phpstan.neon
  serialization/php/text/phpunit.xml
  serialization/php/text/src/TextParseNode.php
  serialization/php/text/src/TextParseNodeFactory.php
  serialization/php/text/src/TextSerializationWriter.php
  serialization/php/text/src/TextSerializationWriterFactory.php
  serialization/php/text/tests/TestEnum.php
  serialization/php/text/tests/TextParseNodeFactoryTest.php
  serialization/php/text/tests/TextParseNodeTest.php
  serialization/php/text/tests/TextSerializationWriterFactoryTest.php
  serialization/php/text/tests/TextSerializationWriterTest.php
  src/Kiota.Builder/Refiners/PhpRefiner.cs
  src/Kiota.Builder/Writers/Php/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Php/PhpConventionService.cs
  tests/Kiota.Builder.Tests/Writers/Php/CodeMethodWriterTests.cs
Labels: PHP

#1556 - fixes the image name for the MCR
  .github/workflows/docker.yml
  CHANGELOG.md
  src/kiota/kiota.csproj
Labels: generator

#1557 adds support for enum descriptions
  CHANGELOG.md
  src/Kiota.Builder/CodeDOM/CodeElement.cs
  src/Kiota.Builder/CodeDOM/CodeEnum.cs
  src/Kiota.Builder/CodeDOM/CodeEnumOption.cs
  src/Kiota.Builder/KiotaBuilder.cs
  src/Kiota.Builder/OpenApiExtensions/OpenApiEnumValuesDescriptionExtension.cs
  src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
  src/Kiota.Builder/Refiners/GoRefiner.cs
  src/Kiota.Builder/Writers/CSharp/CodeEnumWriter.cs
  src/Kiota.Builder/Writers/Go/CodeEnumWriter.cs
  src/Kiota.Builder/Writers/Java/CodeEnumWriter.cs
  src/Kiota.Builder/Writers/Java/JavaConventionService.cs
  src/Kiota.Builder/Writers/Php/CodeEnumWriter.cs
  src/Kiota.Builder/Writers/Ruby/CodeEnumWriter.cs
  src/Kiota.Builder/Writers/Swift/CodeEnumWriter.cs
  src/Kiota.Builder/Writers/TypeScript/CodeEnumWriter.cs
  src/Kiota.Builder/Writers/TypeScript/TypeScriptConventionService.cs
  tests/Kiota.Builder.Tests/CodeDOM/CodeEnumTests.cs
  tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
  tests/Kiota.Builder.Tests/OpenApiExtensions/OpenApiEnumValuesDescriptionExtensionTests.cs
  tests/Kiota.Builder.Tests/Refiners/JavaLanguageRefinerTests.cs
  tests/Kiota.Builder.Tests/Writers/CSharp/CodeEnumWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Go/CodeEnumWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Java/CodeEnumWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Php/CodeEnumWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Ruby/CodeEnumWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/TypeScript/CodeEnumWriterTests.cs
Labels: generator

#1560 bugfix/multiple indexers
  CHANGELOG.md
  abstractions/java/lib/build.gradle
  abstractions/java/lib/src/main/java/com/microsoft/kiota/RequestInformation.java
  src/Kiota.Builder/CodeDOM/CodeClass.cs
  src/Kiota.Builder/CodeDOM/CodeComposedTypeBase.cs
  src/Kiota.Builder/CodeDOM/CodeExclusionType.cs
  src/Kiota.Builder/CodeDOM/CodeMethod.cs
  src/Kiota.Builder/CodeDOM/CodeTypeBase.cs
  src/Kiota.Builder/CodeDOM/CodeUnionType.cs
  src/Kiota.Builder/Extensions/OpenApiSchemaExtensions.cs
  src/Kiota.Builder/Extensions/OpenApiUrlTreeNodeExtensions.cs
  src/Kiota.Builder/Extensions/StringExtensions.cs
  src/Kiota.Builder/KiotaBuilder.cs
  src/Kiota.Builder/Refiners/CSharpReservedNamesProvider.cs
  src/Kiota.Builder/Refiners/CSharpReservedTypesProvider.cs
  src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
  src/Kiota.Builder/Refiners/TypeScriptRefiner.cs
  src/Kiota.Builder/Writers/CSharp/CSharpConventionService.cs
  src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/CommonLanguageConventionService.cs
  src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Go/GoConventionService.cs
  src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Java/JavaConventionService.cs
  src/Kiota.Builder/Writers/Php/PhpConventionService.cs
  src/Kiota.Builder/Writers/Swift/SwiftConventionService.cs
  src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/TypeScript/TypeScriptConventionService.cs
  tests/Kiota.Builder.Tests/CodeDOM/CodeClassTests.cs
  tests/Kiota.Builder.Tests/Extensions/OpenApiSchemaExtensionsTests.cs
  tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
  tests/Kiota.Builder.Tests/Refiners/TypeScriptLanguageRefinerTests.cs
  tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Java/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/TypeScript/CodeMethodWriterTests.cs
Labels: generator

#1496 PHP HttpAdapter Error Handling + Support for 204 responses + Discriminator support
  CHANGELOG.md
  abstractions/php/src/ApiException.php
  abstractions/php/src/RequestAdapter.php
  abstractions/php/src/Serialization/ParsableFactory.php
  abstractions/php/src/Serialization/ParseNode.php
  abstractions/php/src/Serialization/SerializationWriter.php
  http/php/guzzle/phpstan.neon
  http/php/guzzle/phpunit.xml
  http/php/guzzle/src/GuzzleRequestAdapter.php
  http/php/guzzle/tests/GuzzleRequestAdapterTest.php
  serialization/php/json/src/JsonParseNode.php
  serialization/php/json/src/JsonSerializationWriter.php
  serialization/php/json/tests/JsonParseNodeTest.php
  serialization/php/json/tests/Samples/Address.php
  serialization/php/json/tests/Samples/Person.php
  src/Kiota.Builder/Refiners/PhpRefiner.cs
  src/Kiota.Builder/Writers/Php/CodeClassDeclarationWriter.cs
  src/Kiota.Builder/Writers/Php/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Php/PhpConventionService.cs
  tests/Kiota.Builder.Tests/Writers/Php/CodeMethodWriterTests.cs
Labels: PHP

#1575 Fix for null reference exception and incorrect send methods for enums in dotnet
  CHANGELOG.md
  src/Kiota.Builder/KiotaBuilder.cs
  src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
Labels: generator

#1577 CAE support for java
  CHANGELOG.md
  abstractions/java/lib/build.gradle
  abstractions/java/lib/src/main/java/com/microsoft/kiota/authentication/AccessTokenProvider.java
  abstractions/java/lib/src/main/java/com/microsoft/kiota/authentication/AnonymousAuthenticationProvider.java
  abstractions/java/lib/src/main/java/com/microsoft/kiota/authentication/AuthenticationProvider.java
  abstractions/java/lib/src/main/java/com/microsoft/kiota/authentication/BaseBearerTokenAuthenticationProvider.java
  authentication/java/azure/lib/build.gradle
  authentication/java/azure/lib/src/main/java/com/microsoft/kiota/authentication/AzureIdentityAccessTokenProvider.java
  authentication/java/azure/lib/src/test/java/com/microsoft/kiota/authentication/AzureIdentityAccessTokenProviderTest.java
  authentication/java/azure/lib/src/test/java/com/microsoft/kiota/authentication/LibraryTest.java
  http/java/okhttp/lib/build.gradle
  http/java/okhttp/lib/src/main/java/com/microsoft/kiota/http/OkHttpRequestAdapter.java
  http/java/okhttp/lib/src/main/java/com/microsoft/kiota/http/middleware/ParametersNameDecodingHandler.java
  http/java/okhttp/lib/src/test/java/com/microsoft/kiota/http/OkHttpRequestAdapterTest.java
  serialization/java/json/lib/build.gradle
  serialization/java/text/lib/build.gradle
Labels: Java

#1587 Fixes a bug with empty key values for path parameters
  CHANGELOG.md
  src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs
Labels: generator

#1584 PHP - Add support for special characters in query parameters
  CHANGELOG.md
  abstractions/php/composer.json
  abstractions/php/src/QueryParameter.php
  abstractions/php/src/QueryParameterBase.php
  abstractions/php/src/RequestInformation.php
  abstractions/php/tests/RequestInformationTest.php
  http/php/guzzle/src/KiotaClientFactory.php
  http/php/guzzle/src/Middleware/KiotaMiddleware.php
  http/php/guzzle/src/Middleware/Options/ParametersDecodingOption.php
  http/php/guzzle/src/Middleware/ParametersNameDecodingHandler.php
  http/php/guzzle/tests/Middleware/ParametersNameDecodingHandlerTest.php
  src/Kiota.Builder/Refiners/PhpRefiner.cs
  src/Kiota.Builder/Writers/Php/CodePropertyWriter.cs
  tests/Kiota.Builder.Tests/Writers/Php/CodePropertyWriterTests.cs
Labels: PHP

#1473 PHP - uint8, int8 serialization support
  CHANGELOG.md
  abstractions/php/src/Serialization/ParseNode.php
  abstractions/php/src/Serialization/SerializationWriter.php
  abstractions/php/src/Types/Byte.php
  serialization/php/json/composer.json
  serialization/php/json/src/JsonParseNode.php
  serialization/php/json/src/JsonSerializationWriter.php
  serialization/php/json/tests/JsonParseNodeTest.php
  serialization/php/json/tests/JsonSerializationWriterTest.php
  src/Kiota.Builder/Writers/Php/PhpConventionService.cs
  tests/Kiota.Builder.Tests/Writers/Php/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Php/CodePropertyWriterTests.cs
Labels: PHP

#1593 - adds support for enums responses in Go
  CHANGELOG.md
  src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
  tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
Labels: Go

#1594 - fixes a bug where log entries would be missing
  CHANGELOG.md
  src/kiota/KiotaHost.cs
Labels: generator

#1595 builder as package
  .azure-pipelines/ci-build.yml
  src/Kiota.Builder/Kiota.Builder.csproj
  src/Microsoft.OpenApi.Kiota.ApiDescription.Client/Microsoft.OpenApi.Kiota.ApiDescription.Client.nuspec
Labels: generator

#1600 - adds an explicit error message for external references
  CHANGELOG.md
  src/Kiota.Builder/Extensions/OpenApiSchemaExtensions.cs
  tests/Kiota.Builder.Tests/Extensions/OpenApiSchemaExtensionsTests.cs
Labels: generator
