Repository microsoft/kiota, pull requests merged in 2022-04, with the labels that each got.

#1484 - 21 release
  CHANGELOG.md
  src/kiota/kiota.csproj
Labels: generator

#1485 - updates open api libs to latest
  src/Kiota.Builder/Kiota.Builder.csproj
Labels: generator

#1489 - fixes #1483 a bug with models namespace generation
  CHANGELOG.md
  src/Kiota.Builder/KiotaBuilder.cs
  tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Labels: generator

#1491 feature/smaller deserialization
  CHANGELOG.md
  abstractions/java/lib/build.gradle
  abstractions/java/lib/src/main/java/com/microsoft/kiota/serialization/Parsable.java
  serialization/java/json/lib/build.gradle
  serialization/java/json/lib/src/main/java/com/microsoft/kiota/serialization/JsonParseNode.java
  src/Kiota.Builder/KiotaBuilder.cs
  src/Kiota.Builder/Refiners/GoRefiner.cs
  src/Kiota.Builder/Refiners/JavaRefiner.cs
  src/Kiota.Builder/Refiners/TypeScriptRefiner.cs
  src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs
Labels: CSharp, TypeScript, Go, Java, generator

#1477 initial middleware implementations
  CHANGELOG.md
  abstractions/java/lib/build.gradle
  abstractions/java/lib/src/main/java/com/microsoft/kiota/RequestOption.java
  http/java/okhttp/lib/build.gradle
  http/java/okhttp/lib/src/main/java/com/microsoft/kiota/http/KiotaClientFactory.java
  http/java/okhttp/lib/src/main/java/com/microsoft/kiota/http/OkHttpRequestAdapter.java
  http/java/okhttp/lib/src/main/java/com/microsoft/kiota/http/middleware/ChaosHandler.java
  http/java/okhttp/lib/src/main/java/com/microsoft/kiota/http/middleware/RedirectHandler.java
  http/java/okhttp/lib/src/main/java/com/microsoft/kiota/http/middleware/RetryHandler.java
  http/java/okhttp/lib/src/main/java/com/microsoft/kiota/http/middleware/TelemetryHandler.java
  http/java/okhttp/lib/src/main/java/com/microsoft/kiota/http/middleware/options/IShouldRedirect.java
  http/java/okhttp/lib/src/main/java/com/microsoft/kiota/http/middleware/options/IShouldRetry.java
  http/java/okhttp/lib/src/main/java/com/microsoft/kiota/http/middleware/options/RedirectHandlerOption.java
  http/java/okhttp/lib/src/main/java/com/microsoft/kiota/http/middleware/options/RetryHandlerOption.java
  http/java/okhttp/lib/src/main/java/com/microsoft/kiota/http/middleware/options/TelemetryHandlerOption.java
  http/java/okhttp/lib/src/test/java/com/microsoft/kiota/http/middleware/RedirectHandlerTests.java
  http/java/okhttp/lib/src/test/java/com/microsoft/kiota/http/middleware/RetryHandlerTests.java
  http/java/okhttp/lib/src/test/java/com/microsoft/kiota/http/middleware/TelemetryHandlerTests.java
Labels: Java

#1503 - updates the changelog for release
  CHANGELOG.md
  src/kiota/kiota.csproj
Labels: generator

#1512 - fixes a bug where line returns in descriptions could break the generated code
  CHANGELOG.md
  src/Kiota.Builder/Extensions/OpenApiUrlTreeNodeExtensions.cs
  src/Kiota.Builder/KiotaBuilder.cs
  tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Labels: generator

#1498 bugfix/url params names
  CHANGELOG.md
  abstractions/java/lib/build.gradle
  abstractions/java/lib/src/main/java/com/microsoft/kiota/QueryParameter.java
  abstractions/java/lib/src/main/java/com/microsoft/kiota/QueryParametersBase.java
  abstractions/java/lib/src/test/java/com/microsoft/kiota/QueryParametersBaseTest.java
  http/java/okhttp/lib/build.gradle
  http/java/okhttp/lib/src/main/java/com/microsoft/kiota/http/KiotaClientFactory.java
  http/java/okhttp/lib/src/main/java/com/microsoft/kiota/http/middleware/ParametersNameDecodingHandler.java
  http/java/okhttp/lib/src/main/java/com/microsoft/kiota/http/middleware/ParametersNameDecodingOption.java
  http/java/okhttp/lib/src/test/java/com/microsoft/kiota/http/middleware/ParametersNameDecodingHandlerTests.java
  src/Kiota.Builder/CodeDOM/CodeBlock.cs
  src/Kiota.Builder/CodeDOM/CodeIndexer.cs
  src/Kiota.Builder/CodeDOM/CodeMethod.cs
  src/Kiota.Builder/CodeDOM/CodeParameter.cs
  src/Kiota.Builder/CodeDOM/CodeProperty.cs
  src/Kiota.Builder/Extensions/OpenApiUrlTreeNodeExtensions.cs
  src/Kiota.Builder/Extensions/StringExtensions.cs
  src/Kiota.Builder/KiotaBuilder.cs
  src/Kiota.Builder/Refiners/CSharpRefiner.cs
  src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
  src/Kiota.Builder/Refiners/JavaRefiner.cs
  src/Kiota.Builder/Refiners/TypeScriptRefiner.cs
  src/Kiota.Builder/Writers/CSharp/CodeIndexerWriter.cs
  src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/CSharp/CodePropertyWriter.cs
  src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Go/CodePropertyWriter.cs
  src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Java/CodePropertyWriter.cs
  src/Kiota.Builder/Writers/Php/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Ruby/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/TypeScript/CodePropertyWriter.cs
  src/Kiota.Builder/Writers/TypeScript/TypeScriptConventionService.cs
  src/Kiota.Builder/Writers/TypeScript/TypeScriptRelativeImportManager.cs
  tests/Kiota.Builder.IntegrationTests/GenerateSample.cs
  tests/Kiota.Builder.Tests/Extensions/OpenApiUrlTreeNodeExtensionsTests.cs
  tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
  tests/Kiota.Builder.Tests/Refiners/TypeScriptLanguageRefinerTests.cs
  tests/Kiota.Builder.Tests/Writers/CSharp/CodeIndexerWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/CSharp/CodePropertyWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Go/CodePropertyWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Java/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Java/CodePropertyWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Php/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Ruby/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/TypeScript/CodeMethodWriterTests.cs
Labels: generator

#1514 - fixes a bug where complex types path parameters would fail to generate
  CHANGELOG.md
  src/Kiota.Builder/KiotaBuilder.cs
  tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Labels: generator

#1515 - Fixes a bug where Go serialization/deserialization method would generate invalid accessor names
  CHANGELOG.md
  src/Kiota.Builder/CodeDOM/CodeProperty.cs
  src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
Labels: Go

#1524 - fixes #1523 the required go version
  docs/get-started/go.md
Labels: Go

#1525 - release 0.0.23
  CHANGELOG.md
  src/kiota/kiota.csproj
Labels: generator

#1520 request config revamp
  CHANGELOG.md
  abstractions/java/lib/build.gradle
  abstractions/java/lib/src/main/java/com/microsoft/kiota/QueryParametersBase.java
  abstractions/java/lib/src/main/java/com/microsoft/kiota/RequestInformation.java
  abstractions/java/lib/src/main/java/com/microsoft/kiota/authentication/BaseBearerTokenAuthenticationProvider.java
  abstractions/java/lib/src/test/java/com/microsoft/kiota/QueryParametersBaseTest.java
  abstractions/java/lib/src/test/java/com/microsoft/kiota/RequestInformationTest.java
  http/java/okhttp/lib/build.gradle
  http/java/okhttp/lib/src/main/java/com/microsoft/kiota/http/OkHttpRequestAdapter.java
  http/java/okhttp/lib/src/test/java/com/microsoft/kiota/http/middleware/TelemetryHandlerTests.java
  src/Kiota.Builder/CodeDOM/CodeClass.cs
  src/Kiota.Builder/CodeDOM/CodeParameter.cs
  src/Kiota.Builder/CodeDOM/CodeProperty.cs
  src/Kiota.Builder/CodeParameterOrderComparer.cs
  src/Kiota.Builder/KiotaBuilder.cs
  src/Kiota.Builder/Refiners/CSharpRefiner.cs
  src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
  src/Kiota.Builder/Refiners/GoRefiner.cs
  src/Kiota.Builder/Refiners/JavaRefiner.cs
  src/Kiota.Builder/Refiners/PhpRefiner.cs
  src/Kiota.Builder/Refiners/SwiftRefiner.cs
  src/Kiota.Builder/Refiners/TypeScriptRefiner.cs
  src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/CSharp/CodePropertyWriter.cs
  src/Kiota.Builder/Writers/CodeParameterExtension.cs
  src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Java/CodePropertyWriter.cs
  src/Kiota.Builder/Writers/Php/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Php/PhpConventionService.cs
  src/Kiota.Builder/Writers/RequestParams.cs
  src/Kiota.Builder/Writers/Ruby/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Shell/ShellCodeMethodWriter.cs
  src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs
  tests/Kiota.Builder.Tests/CodeDOM/CodeParameterTests.cs
  tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
  tests/Kiota.Builder.Tests/Refiners/GoLanguageRefinerTests.cs
  tests/Kiota.Builder.Tests/Refiners/JavaLanguageRefinerTests.cs
  tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/CommonLanguageConventionServiceTests.cs
  tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Go/GoConventionServiceTests.cs
  tests/Kiota.Builder.Tests/Writers/Go/NamespaceExtensionsTests.cs
  tests/Kiota.Builder.Tests/Writers/Java/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Php/CodeClassDeclarationWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Php/CodeClassEndWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Php/CodeEnumWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Php/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Php/CodePropertyWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Php/PhpWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Ruby/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Shell/ShellCodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/StringExtensionsTests.cs
  tests/Kiota.Builder.Tests/Writers/TypeScript/CodeMethodWriterTests.cs
Labels: CSharp, TypeScript, Python, PHP, Go, Ruby, Java, generator, CLI, Swift
