Repository microsoft/kiota, pull requests merged in 2022-09, with the labels that each got.

#1806 Fixes to require statements in generated code
  CHANGELOG.md
  src/Kiota.Builder/Refiners/RubyRefiner.cs
  src/Kiota.Builder/Writers/Ruby/CodeMethodWriter.cs
  tests/Kiota.Builder.Tests/Refiners/RubyLanguageRefinerTests.cs
Labels: Ruby

#1809 Update to Ruby Getting Started
  docs/get-started/ruby.md
Labels: Ruby

#1811 Formatting Changes
  docs/get-started/ruby.md
Labels: Ruby

#1820 adds support for range responses
  CHANGELOG.md
  docs/extending/statuscodes.md
  src/Kiota.Builder/Extensions/OpenApiOperationExtensions.cs
  src/Kiota.Builder/KiotaBuilder.cs
  tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Labels: generator

#1825 - bumps versions and updates changelog for o five release
  CHANGELOG.md
  src/Kiota.Builder/Kiota.Builder.csproj
  src/kiota/kiota.csproj
Labels: generator

#1829 feature/readonly
  CHANGELOG.md
  src/Kiota.Builder/KiotaBuilder.cs
  src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/CodeClassExtensions.cs
  src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Php/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Python/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Ruby/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs
  tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
  tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Java/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Python/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Ruby/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/TypeScript/CodeMethodWriterTests.cs
Labels: generator

#1831 bugfix/parse node type
  CHANGELOG.md
  src/Kiota.Builder/Kiota.Builder.csproj
  src/Kiota.Builder/Refiners/GoRefiner.cs
  src/Kiota.Builder/Refiners/JavaRefiner.cs
  src/Kiota.Builder/Refiners/PhpRefiner.cs
  src/Kiota.Builder/Refiners/PythonRefiner.cs
  src/Kiota.Builder/Refiners/RubyRefiner.cs
  src/Kiota.Builder/Refiners/SwiftRefiner.cs
  src/Kiota.Builder/Refiners/TypeScriptRefiner.cs
  src/kiota/kiota.csproj
Labels: bug, generator

#1837 bugfix/discriminator mappings
  CHANGELOG.md
  src/Kiota.Builder/CodeDOM/CodeClass.cs
  src/Kiota.Builder/CodeDOM/DiscriminatorInformation.cs
  src/Kiota.Builder/KiotaBuilder.cs
  src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
  tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Labels: bug, generator

#1850 - fixes a bug where Java request options type could conflict with generated types.
  CHANGELOG.md
  src/Kiota.Builder/Refiners/JavaRefiner.cs
  src/Kiota.Builder/Writers/Java/JavaConventionService.cs
Labels: Java

#1848 Generate go de-serializers with generic helpers
  CHANGELOG.md
  src/Kiota.Builder/Refiners/GoRefiner.cs
  src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Go/GoConventionService.cs
  tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
Labels: Go

#1854 bugfix/generation fixes
  CHANGELOG.md
  src/Kiota.Builder/CodeDOM/CodeBlock.cs
  src/Kiota.Builder/Extensions/OpenApiSchemaExtensions.cs
  src/Kiota.Builder/KiotaBuilder.cs
  src/Kiota.Builder/Refiners/CSharpRefiner.cs
  src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
  src/Kiota.Builder/Refiners/GoRefiner.cs
  src/Kiota.Builder/Refiners/ILanguageRefiner.cs
  src/Kiota.Builder/Refiners/JavaRefiner.cs
  src/Kiota.Builder/Refiners/PhpRefiner.cs
  src/Kiota.Builder/Refiners/PythonRefiner.cs
  src/Kiota.Builder/Refiners/RubyRefiner.cs
  src/Kiota.Builder/Refiners/ShellRefiner.cs
  src/Kiota.Builder/Refiners/SwiftRefiner.cs
  src/Kiota.Builder/Refiners/TypeScriptRefiner.cs
  src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Java/CodePropertyWriter.cs
  src/Kiota.Builder/Writers/Php/CodeMethodWriter.cs
  tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
  tests/Kiota.Builder.Tests/Refiners/CSharpLanguageRefinerTests.cs
  tests/Kiota.Builder.Tests/Refiners/GoLanguageRefinerTests.cs
  tests/Kiota.Builder.Tests/Refiners/JavaLanguageRefinerTests.cs
  tests/Kiota.Builder.Tests/Refiners/PhpLanguageRefinerTests.cs
  tests/Kiota.Builder.Tests/Refiners/PythonLanguageRefinerTests.cs
  tests/Kiota.Builder.Tests/Refiners/RubyLanguageRefinerTests.cs
  tests/Kiota.Builder.Tests/Refiners/ShellRefinerTests.cs
  tests/Kiota.Builder.Tests/Refiners/TypeScriptLanguageRefinerTests.cs
  tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Java/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Php/CodeClassDeclarationWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Php/CodeEnumWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Php/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Php/CodePropertyWriterTests.cs
Labels: bug, CSharp, PHP, Go, Java

#1841 feature/observability
  CHANGELOG.md
  src/Kiota.Builder/Refiners/GoRefiner.cs
  src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
  tests/Kiota.Builder.Tests/Refiners/GoLanguageRefinerTests.cs
  tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
Labels: Go

#1862 - fixes flaky ruby unit tests
  tests/Kiota.Builder.Tests/Refiners/RubyLanguageRefinerTests.cs
Labels: bug, Ruby

#1863 adds support for filtering paths items during generation
  CHANGELOG.md
  docs/using.md
  src/Kiota.Builder/GenerationConfiguration.cs
  src/Kiota.Builder/Kiota.Builder.csproj
  src/Kiota.Builder/KiotaBuilder.cs
  src/kiota/KiotaCommandHandler.cs
  src/kiota/KiotaHost.cs
  tests/Kiota.Builder.Tests/Kiota.Builder.Tests.csproj
  tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Labels: enhancement, generator
