Repository microsoft/kiota, pull requests merged in 2022-03, with the labels that each got.

#1251 Samwelkanda/python requests request adapter
  .github/workflows/http-python-requests.yml
  CHANGELOG.md
  README.md
  http/python/requests/.gitignore
  http/python/requests/.pylintrc
  http/python/requests/LICENSE
  http/python/requests/Pipfile
  http/python/requests/Pipfile.lock
  http/python/requests/README.md
  http/python/requests/http_requests/__init__.py
  http/python/requests/http_requests/_version.py
  http/python/requests/http_requests/kiota_client.py
  http/python/requests/http_requests/kiota_client_factory.py
  http/python/requests/http_requests/middleware/__init__.py
  http/python/requests/http_requests/middleware/middleware.py
  http/python/requests/http_requests/middleware/options/__init__.py
  http/python/requests/http_requests/middleware/options/retry_handler_option.py
  http/python/requests/http_requests/middleware/redirect_handler.py
  http/python/requests/http_requests/middleware/retry_handler.py
  http/python/requests/http_requests/requests_request_adapter.py
  http/python/requests/pyproject.toml
  http/python/requests/tests/__init__.py
  http/python/requests/tests/helpers/__init__.py
  http/python/requests/tests/helpers/office_location.py
  http/python/requests/tests/helpers/user.py
  http/python/requests/tests/middleware/__init__.py
  http/python/requests/tests/middleware/test_retry_handler.py
  http/python/requests/tests/test_kiota_client.py
  http/python/requests/tests/test_kiota_client_factory.py
  http/python/requests/tests/test_requests_request_adapter.py
Labels: Python

#1314 - updates lock files for discriminator release
  http/go/nethttp/go.mod
  http/go/nethttp/go.sum
  http/typescript/fetch/package-lock.json
  serialization/go/json/go.mod
  serialization/go/json/go.sum
  serialization/typescript/json/package-lock.json
Labels: TypeScript, Go

#1311 - Fixed a bug in Go generator where temporary url template parameters would not be used preventing the use of raw urls
  CHANGELOG.md
  abstractions/go/authentication/anonymous_authentication_provider.go
  abstractions/go/authentication/authentication_provider.go
  abstractions/go/authentication/base_bearer_token_authentication_provider.go
  abstractions/go/request_adapter.go
  abstractions/go/request_information_test.go
  http/go/nethttp/nethttp_request_adapter.go
  src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
  tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
Labels: Go

#1291 Add query option to commands with responses
  CHANGELOG.md
  src/Kiota.Builder/Writers/Shell/ShellCodeMethodWriter.cs
  tests/Kiota.Builder.Tests/Writers/Shell/ShellCodeMethodWriterTests.cs
Labels: CLI

#1323 - bumps version number for kiota release
  CHANGELOG.md
  src/kiota/kiota.csproj
Labels: generator

#1321 Feat/output formatter options
  CHANGELOG.md
  cli/commons/src/Microsoft.Kiota.Cli.Commons/IO/IOutputFormatter.cs
  cli/commons/src/Microsoft.Kiota.Cli.Commons/IO/JsonOutputFormatterOptions.cs
  cli/commons/src/Microsoft.Kiota.Cli.Commons/IO/OutputFormatterOptions.cs
  cli/commons/src/Microsoft.Kiota.Cli.Commons/IO/TableOutputFormatterOptions.cs
  cli/commons/src/Microsoft.Kiota.Cli.Commons/Microsoft.Kiota.Cli.Commons.csproj
Labels: CLI

#1322 - upgrades gradle wrapper
  abstractions/java/gradle/wrapper/gradle-wrapper.jar
  abstractions/java/gradle/wrapper/gradle-wrapper.properties
  abstractions/java/gradlew
  authentication/java/azure/gradle/wrapper/gradle-wrapper.jar
  authentication/java/azure/gradle/wrapper/gradle-wrapper.properties
  authentication/java/azure/gradlew
  http/java/okhttp/gradle/wrapper/gradle-wrapper.jar
  http/java/okhttp/gradle/wrapper/gradle-wrapper.properties
  http/java/okhttp/gradlew
  serialization/java/json/gradle/wrapper/gradle-wrapper.jar
  serialization/java/json/gradle/wrapper/gradle-wrapper.properties
  serialization/java/json/gradlew
Labels: Java

#1315 parsable interface split
  abstractions/dotnet/src/Microsoft.Kiota.Abstractions.csproj
  abstractions/dotnet/src/serialization/IAdditionalDataHolder.cs
  abstractions/dotnet/src/serialization/IParsable.cs
  abstractions/go/serialization/additional_data_holder.go
  abstractions/go/serialization/parsable.go
  abstractions/java/lib/build.gradle
  abstractions/java/lib/src/main/java/com/microsoft/kiota/serialization/AdditionalDataHolder.java
  abstractions/java/lib/src/main/java/com/microsoft/kiota/serialization/Parsable.java
  abstractions/typescript/package-lock.json
  abstractions/typescript/package.json
  abstractions/typescript/src/serialization/additionalDataHolder.ts
  abstractions/typescript/src/serialization/index.ts
  abstractions/typescript/src/serialization/parsable.ts
  docs/extending/kiotaabstractions.md
  docs/extending/serialization.md
  http/java/okhttp/lib/.classpath
  serialization/dotnet/json/Microsoft.Kiota.Serialization.Json.Tests/Mocks/TestEntity.cs
  serialization/dotnet/json/src/JsonParseNode.cs
  serialization/dotnet/json/src/Microsoft.Kiota.Serialization.Json.csproj
  serialization/go/json/json_parse_node.go
  serialization/java/json/lib/build.gradle
  serialization/java/json/lib/src/main/java/com/microsoft/kiota/serialization/JsonParseNode.java
  serialization/typescript/json/package-lock.json
  serialization/typescript/json/package.json
  serialization/typescript/json/src/jsonParseNode.ts
  src/Kiota.Builder/CodeDOM/CodeClass.cs
  src/Kiota.Builder/KiotaBuilder.cs
  src/Kiota.Builder/Refiners/CSharpRefiner.cs
  src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
  src/Kiota.Builder/Refiners/GoRefiner.cs
  src/Kiota.Builder/Refiners/JavaRefiner.cs
  src/Kiota.Builder/Refiners/RubyRefiner.cs
  src/Kiota.Builder/Refiners/TypeScriptRefiner.cs
  src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Go/CodeInterfaceDeclarationWriter.cs
  src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs
  tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
  tests/Kiota.Builder.Tests/Refiners/JavaLanguageRefinerTests.cs
Labels: CSharp, TypeScript, Go, Java, generator

#1330 - lock file updates
  serialization/go/json/go.mod
  serialization/go/json/go.sum
  serialization/typescript/json/package-lock.json
Labels: TypeScript, Go

#1340 Samwelkanda/bugfix python azure authentication
  CHANGELOG.md
  authentication/python/azure/Pipfile
  authentication/python/azure/Pipfile.lock
  authentication/python/azure/authentication_azure/_version.py
  authentication/python/azure/authentication_azure/azure_identity_access_token_provider.py
  authentication/python/azure/authentication_azure/azure_identity_authentication_provider.py
Labels: Python

#1344 better error display
  CHANGELOG.md
  src/Kiota.Builder/CodeRenderer.cs
  src/Kiota.Builder/KiotaBuilder.cs
  src/kiota/KiotaHost.cs
  tests/Kiota.Builder.IntegrationTests/GenerateSample.cs
  tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Labels: generator

#1355 Generation fixes in Dotnet and Go
  CHANGELOG.md
  src/Kiota.Builder/CodeDOM/ProprietableBlock.cs
  src/Kiota.Builder/KiotaBuilder.cs
  src/Kiota.Builder/Writers/Go/CodeProprietableBlockDeclarationWriter.cs
  tests/Kiota.Builder.Tests/Refiners/JavaLanguageRefinerTests.cs
Labels: CSharp, Go, generator

#1353 Fixes PHP core bugs
  CHANGELOG.md
  abstractions/php/src/Authentication/BaseBearerTokenAuthenticationProvider.php
  abstractions/php/src/RequestInformation.php
  http/php/guzzle/src/GuzzleRequestAdapter.php
  http/php/guzzle/src/KiotaClientFactory.php
  http/php/guzzle/tests/GuzzleRequestAdapterTest.php
  serialization/php/json/src/JsonParseNode.php
Labels: PHP

#1358 - fixes a bug where implements generation would not be deterministic
  CHANGELOG.md
  src/Kiota.Builder/CodeDOM/CodeBlock.cs
  src/Kiota.Builder/CodeDOM/CodeClass.cs
  src/Kiota.Builder/CodeDOM/CodeMethod.cs
  src/Kiota.Builder/CodeDOM/CodeNamespace.cs
  src/Kiota.Builder/CodeDOM/ProprietableBlock.cs
  src/Kiota.Builder/CodeElementOrderComparerWithExternalMethods.cs
  src/Kiota.Builder/CodeParameterOrderComparer.cs
  src/Kiota.Builder/KiotaBuilder.cs
  src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
  src/Kiota.Builder/Refiners/GoRefiner.cs
  src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
  tests/Kiota.Builder.Tests/CodeDOM/CodeBlockTests.cs
  tests/Kiota.Builder.Tests/CodeDOM/CodeClassTests.cs
  tests/Kiota.Builder.Tests/CodeDOM/CodeMethodTests.cs
  tests/Kiota.Builder.Tests/CodeDOM/CodeNamespaceTests.cs
  tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
  tests/Kiota.Builder.Tests/Refiners/CSharpLanguageRefinerTests.cs
  tests/Kiota.Builder.Tests/Refiners/GoLanguageRefinerTests.cs
  tests/Kiota.Builder.Tests/Refiners/JavaLanguageRefinerTests.cs
  tests/Kiota.Builder.Tests/Refiners/TypeScriptLanguageRefinerTests.cs
  tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Java/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/TypeScript/CodeFunctionWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/TypeScript/CodeMethodWriterTests.cs
Labels: Go, generator

#1326 Feat/output formatter options
  CHANGELOG.md
  cli/commons/src/Microsoft.Kiota.Cli.Commons.Tests/IO/JmesPathOutputFilterTest.cs
  cli/commons/src/Microsoft.Kiota.Cli.Commons.Tests/IO/JsonOutputFormatterTest.cs
  cli/commons/src/Microsoft.Kiota.Cli.Commons.Tests/IO/OutputFormatterFactoryTest.cs
  cli/commons/src/Microsoft.Kiota.Cli.Commons.Tests/IO/TableOutputFormatterTest.cs
  cli/commons/src/Microsoft.Kiota.Cli.Commons.Tests/Microsoft.Kiota.Cli.Commons.Tests.csproj
  cli/commons/src/Microsoft.Kiota.Cli.Commons/IO/FormatterOptionsModel.cs
  cli/commons/src/Microsoft.Kiota.Cli.Commons/IO/FormatterTypeExtensions.cs
  cli/commons/src/Microsoft.Kiota.Cli.Commons/IO/IJsonOutputFormatterOptions.cs
  cli/commons/src/Microsoft.Kiota.Cli.Commons/IO/IOutputFilter.cs
  cli/commons/src/Microsoft.Kiota.Cli.Commons/IO/IOutputFormatter.cs
  cli/commons/src/Microsoft.Kiota.Cli.Commons/IO/IOutputFormatterOptions.cs
  cli/commons/src/Microsoft.Kiota.Cli.Commons/IO/ITableOutputFormatterOptions.cs
  cli/commons/src/Microsoft.Kiota.Cli.Commons/IO/JmesPathOutputFilter.cs
  cli/commons/src/Microsoft.Kiota.Cli.Commons/IO/JsonOutputFormatter.cs
  cli/commons/src/Microsoft.Kiota.Cli.Commons/IO/JsonOutputFormatterOptions.cs
  cli/commons/src/Microsoft.Kiota.Cli.Commons/IO/OutputFormatterFactory.cs
  cli/commons/src/Microsoft.Kiota.Cli.Commons/IO/OutputFormatterOptions.cs
  cli/commons/src/Microsoft.Kiota.Cli.Commons/IO/TableOutputFormatter.cs
  cli/commons/src/Microsoft.Kiota.Cli.Commons/IO/TableOutputFormatterOptions.cs
  cli/commons/src/Microsoft.Kiota.Cli.Commons/Microsoft.Kiota.Cli.Commons.csproj
  src/Kiota.Builder/Writers/Shell/ShellCodeMethodWriter.cs
  tests/Kiota.Builder.Tests/Writers/Shell/ShellCodeMethodWriterTests.cs
Labels: CLI

#1365 - fixes #1272 empty error schema generation fail
  CHANGELOG.md
  src/Kiota.Builder/KiotaBuilder.cs
  tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Labels: generator

#1367 adds missing type mappings
  CHANGELOG.md
  abstractions/dotnet/src/Microsoft.Kiota.Abstractions.csproj
  abstractions/dotnet/src/serialization/IParseNode.cs
  abstractions/dotnet/src/serialization/ISerializationWriter.cs
  abstractions/go/serialization/parse_node.go
  abstractions/go/serialization/serialization_writer.go
  abstractions/java/lib/build.gradle
  abstractions/java/lib/src/main/java/com/microsoft/kiota/serialization/ParseNode.java
  abstractions/java/lib/src/main/java/com/microsoft/kiota/serialization/SerializationWriter.java
  serialization/dotnet/json/src/JsonParseNode.cs
  serialization/dotnet/json/src/JsonSerializationWriter.cs
  serialization/dotnet/json/src/Microsoft.Kiota.Serialization.Json.csproj
  serialization/go/json/json_parse_node.go
  serialization/go/json/json_serialization_writer.go
  serialization/java/json/lib/build.gradle
  serialization/java/json/lib/src/main/java/com/microsoft/kiota/serialization/JsonParseNode.java
  serialization/java/json/lib/src/main/java/com/microsoft/kiota/serialization/JsonSerializationWriter.java
  src/Kiota.Builder/KiotaBuilder.cs
  src/Kiota.Builder/Refiners/JavaRefiner.cs
  src/Kiota.Builder/Writers/CSharp/CSharpConventionService.cs
  src/Kiota.Builder/Writers/Go/GoConventionService.cs
  src/Kiota.Builder/Writers/Java/JavaConventionService.cs
  src/Kiota.Builder/Writers/TypeScript/TypeScriptConventionService.cs
  tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
  tests/Kiota.Builder.Tests/Refiners/JavaLanguageRefinerTests.cs
Labels: CSharp, TypeScript, Go, Java, generator

#1376 - updates lock file for release
  serialization/go/json/go.mod
  serialization/go/json/go.sum
Labels: Go

#1377 - release 0-0-18
  CHANGELOG.md
  src/kiota/kiota.csproj
Labels: generator

#1379 - adds a clean ouput argument
  CHANGELOG.md
  docs/using.md
  src/Kiota.Builder/GenerationConfiguration.cs
  src/Kiota.Builder/KiotaBuilder.cs
  src/kiota/KiotaHost.cs
Labels: generator

#1378 - fixes #1273 a bug where unnecessary namespaces would be added to models generation
  CHANGELOG.md
  src/Kiota.Builder/KiotaBuilder.cs
  tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Labels: generator

#1391 - fixes a bug for go byt arrays
  CHANGELOG.md
  src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Go/GoConventionService.cs
Labels: Go

#1392 - fixes a bug where integers would not be recognized when type is not number
  CHANGELOG.md
  src/Kiota.Builder/KiotaBuilder.cs
  tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Labels: generator

#1396 - fixes #990 a bug where the generator would introduce unnecessary union types for nullables
  CHANGELOG.md
  src/Kiota.Builder/KiotaBuilder.cs
  tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Labels: generator

#1394 - fixes #1393 a bug where models descriptions would not be deterministic
  CHANGELOG.md
  src/Kiota.Builder/KiotaBuilder.cs
  tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Labels: generator

#1381 - fixes #1270 a bug where missing schema title would make union types fail
  CHANGELOG.md
  src/Kiota.Builder/Extensions/OpenApiSchemaExtensions.cs
  src/Kiota.Builder/KiotaBuilder.cs
  tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Labels: generator

#1412 - releases kiota 0.0.19
  CHANGELOG.md
  src/kiota/kiota.csproj
Labels: generator

#1413 go nil check serialization fix
  CHANGELOG.md
  abstractions/go/serialization/parsable.go
  serialization/go/json/json_serialization_writer.go
  src/Kiota.Builder/CodeDOM/CodeMethod.cs
  src/Kiota.Builder/Refiners/GoRefiner.cs
  src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
Labels: Go

#1274 Typescript - introducing index files namespace wise fixing circular dependency
  CHANGELOG.md
  src/Kiota.Builder/CodeDOM/CodeNamespace.cs
  src/Kiota.Builder/CodeRenderers/CodeRenderer.cs
  src/Kiota.Builder/CodeRenderers/TypeScriptCodeRenderer.cs
  src/Kiota.Builder/GenerationConfiguration.cs
  src/Kiota.Builder/KiotaBuilder.cs
  src/Kiota.Builder/Writers/RelativeImportManager.cs
  src/Kiota.Builder/Writers/TypeScript/CodeNameSpaceWriter.cs
  src/Kiota.Builder/Writers/TypeScript/CodeUsingWriter.cs
  src/Kiota.Builder/Writers/TypeScript/TypeScriptRelativeImportManager.cs
  src/Kiota.Builder/Writers/TypeScript/TypeScriptWriter.cs
  tests/Kiota.Builder.Tests/Writers/TypeScript/CodeNamespaceWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/TypeScriptRelativeImportManagerTests.cs
Labels: TypeScript

#1328 Using record for additional data
  CHANGELOG.md
  abstractions/typescript/package-lock.json
  abstractions/typescript/package.json
  abstractions/typescript/src/serialization/additionalDataHolder.ts
  abstractions/typescript/src/serialization/parsable.ts
  abstractions/typescript/src/serialization/serializationWriter.ts
  serialization/typescript/json/package.json
  serialization/typescript/json/src/jsonParseNode.ts
  serialization/typescript/json/src/jsonSerializationWriter.ts
  serialization/typescript/text/package.json
  serialization/typescript/text/src/textSerializationWriter.ts
  src/Kiota.Builder/Refiners/TypeScriptRefiner.cs
  src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs
Labels: TypeScript

#1415 - updates lock files
  serialization/typescript/json/package-lock.json
  serialization/typescript/text/package-lock.json
Labels: TypeScript

#728 TypeScript - isomorphic setup, first set of middlewares
  CHANGELOG.md
  http/typescript/fetch/.eslintignore
  http/typescript/fetch/.npmignore
  http/typescript/fetch/docs/design/isomorphic.md
  http/typescript/fetch/docs/design/testing.md
  http/typescript/fetch/dom.shim.d.ts
  http/typescript/fetch/karma.conf.js
  http/typescript/fetch/package-lock.json
  http/typescript/fetch/package.json
  http/typescript/fetch/rollup.config.js
  http/typescript/fetch/src/browser/index.ts
  http/typescript/fetch/src/fetchRequestAdapter.ts
  http/typescript/fetch/src/httpClient.ts
  http/typescript/fetch/src/index.ts
  http/typescript/fetch/src/kiotaClientFactory.ts
  http/typescript/fetch/src/middleware.ts
  http/typescript/fetch/src/middlewares/browser/middlewareFactory.ts
  http/typescript/fetch/src/middlewares/customFetchHandler.ts
  http/typescript/fetch/src/middlewares/middleware.ts
  http/typescript/fetch/src/middlewares/middlewareFactory.ts
  http/typescript/fetch/src/middlewares/options/redirectHandlerOptions.ts
  http/typescript/fetch/src/middlewares/options/retryHandlerOptions.ts
  http/typescript/fetch/src/middlewares/options/telemetryHandlerOptions.ts
  http/typescript/fetch/src/middlewares/redirectHandler.ts
  http/typescript/fetch/src/middlewares/retryHandler.ts
  http/typescript/fetch/src/middlewares/telemetryHandler.ts
  http/typescript/fetch/src/utils/fetchDefinitions.ts
  http/typescript/fetch/src/utils/headersUtil.ts
  http/typescript/fetch/src/utils/referDom.d.ts
  http/typescript/fetch/test/browser/MiddlewareFactory.ts
  http/typescript/fetch/test/browser/httpClient.ts
  http/typescript/fetch/test/browser/index.ts
  http/typescript/fetch/test/common/middleware/RetryHandler.ts
  http/typescript/fetch/test/common/middleware/RetryHandlerOptions.ts
  http/typescript/fetch/test/common/middleware/dummyFetchHandler.ts
  http/typescript/fetch/test/common/middleware/headersUtil.ts
  http/typescript/fetch/test/node/MiddlewareFactory.ts
  http/typescript/fetch/test/node/RedirectHandler.ts
  http/typescript/fetch/test/node/RedirectHandlerOptions.ts
  http/typescript/fetch/test/node/httpClient.ts
  http/typescript/fetch/test/testUtils.ts
  http/typescript/fetch/tsconfig.base.json
  http/typescript/fetch/tsconfig.cjs.json
  http/typescript/fetch/tsconfig.cjs.test.json
  http/typescript/fetch/tsconfig.es.json
  http/typescript/fetch/tsconfig.es.test.json
Labels: TypeScript

#1408 - fixes a bug where service errors would not deserialize properly for typescript
  CHANGELOG.md
  abstractions/typescript/package-lock.json
  abstractions/typescript/package.json
  abstractions/typescript/src/apiError.ts
  serialization/typescript/json/package-lock.json
  serialization/typescript/json/package.json
  serialization/typescript/json/src/jsonParseNode.ts
  src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs
Labels: TypeScript

#1425 Update package lock json
  serialization/typescript/json/package-lock.json
  serialization/typescript/json/package.json
Labels: TypeScript

#1435 fixes dev container configuration
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .vscode/settings.json
Labels: generator

#1440 - removes token instructions from typescript getting started
  docs/get-started/typescript.md
Labels: TypeScript

#1441 multiple schema type generation fixes
  CHANGELOG.md
  src/Kiota.Builder/Extensions/OpenApiSchemaExtensions.cs
  src/Kiota.Builder/KiotaBuilder.cs
  src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
  tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Labels: generator

#1442 - maps decimal type to number in typescript
  CHANGELOG.md
  src/Kiota.Builder/Writers/TypeScript/TypeScriptConventionService.cs
Labels: TypeScript

#1446 - prepares double o twenty release
  CHANGELOG.md
  src/kiota/kiota.csproj
Labels: generator

#1455 bugfix/id detection
  CHANGELOG.md
  src/Kiota.Builder/Extensions/OpenApiUrlTreeNodeExtensions.cs
  tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Labels: generator

#1457 add support for 204
  CHANGELOG.md
  http/go/nethttp/nethttp_request_adapter.go
  http/java/okhttp/lib/build.gradle
  http/java/okhttp/lib/src/main/java/com/microsoft/kiota/http/OkHttpRequestAdapter.java
  tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Labels: generator

#1444 swift support
  .github/workflows/abstractions-swift.yml
  .vscode/launch.json
  CHANGELOG.md
  README.md
  abstractions/swift/.gitignore
  abstractions/swift/MicrosoftKiotaAbstractions.podspec
  abstractions/swift/MicrosoftKiotaAbstractions.xcworkspace/contents.xcworkspacedata
  abstractions/swift/Package.resolved
  abstractions/swift/Package.swift
  abstractions/swift/Podfile
  abstractions/swift/Source/MicrosoftKiotaAbstractions/ApiClientBuilder.swift
  abstractions/swift/Source/MicrosoftKiotaAbstractions/ApiError.swift
  abstractions/swift/Source/MicrosoftKiotaAbstractions/Authentication/AccessTokenProvider.swift
  abstractions/swift/Source/MicrosoftKiotaAbstractions/Authentication/AllowedHostsValidator.swift
  abstractions/swift/Source/MicrosoftKiotaAbstractions/Authentication/AnonymousAuthenticationProvider.swift
  abstractions/swift/Source/MicrosoftKiotaAbstractions/Authentication/AuthenticationProvider.swift
  abstractions/swift/Source/MicrosoftKiotaAbstractions/Authentication/BaseBearerAuthenticationProvider.swift
  abstractions/swift/Source/MicrosoftKiotaAbstractions/HttpMethod.swift
  abstractions/swift/Source/MicrosoftKiotaAbstractions/RequestAdapter.swift
  abstractions/swift/Source/MicrosoftKiotaAbstractions/RequestInformation.swift
  abstractions/swift/Source/MicrosoftKiotaAbstractions/RequestOption.swift
  abstractions/swift/Source/MicrosoftKiotaAbstractions/Serialization/AdditionalDataHolder.swift
  abstractions/swift/Source/MicrosoftKiotaAbstractions/Serialization/Parsable.swift
  abstractions/swift/Source/MicrosoftKiotaAbstractions/Serialization/ParseNode.swift
  abstractions/swift/Source/MicrosoftKiotaAbstractions/Serialization/ParseNodeFactory.swift
  abstractions/swift/Source/MicrosoftKiotaAbstractions/Serialization/ParseNodeFactoryRegistry.swift
  abstractions/swift/Source/MicrosoftKiotaAbstractions/Serialization/SerializationWriter.swift
  abstractions/swift/Source/MicrosoftKiotaAbstractions/Serialization/SerializationWriterFactory.swift
  abstractions/swift/Source/MicrosoftKiotaAbstractions/Serialization/SerializationWriterFactoryRegistry.swift
  abstractions/swift/Tests/MicrosoftKiotaAbstractionsTests/RequestInformationTests.swift
  src/Kiota.Builder/CodeDOM/CodeClass.cs
  src/Kiota.Builder/CodeDOM/CodeNamespace.cs
  src/Kiota.Builder/CodeDOM/NamespaceDifferentialTracker.cs
  src/Kiota.Builder/Extensions/StringExtensions.cs
  src/Kiota.Builder/GenerationConfiguration.cs
  src/Kiota.Builder/GenerationLanguage.cs
  src/Kiota.Builder/PathSegmenters/SwiftPathSegmenter.cs
  src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
  src/Kiota.Builder/Refiners/ILanguageRefiner.cs
  src/Kiota.Builder/Refiners/SwiftRefiner.cs
  src/Kiota.Builder/Refiners/SwiftReservedNamesProvider.cs
  src/Kiota.Builder/Writers/LanguageWriter.cs
  src/Kiota.Builder/Writers/RelativeImportManager.cs
  src/Kiota.Builder/Writers/Swift/CodeBlockEndWriter.cs
  src/Kiota.Builder/Writers/Swift/CodeClassDeclarationWriter.cs
  src/Kiota.Builder/Writers/Swift/CodeEnumWriter.cs
  src/Kiota.Builder/Writers/Swift/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Swift/CodeNamespaceWriter.cs
  src/Kiota.Builder/Writers/Swift/CodePropertyWriter.cs
  src/Kiota.Builder/Writers/Swift/CodeProprietableBlockDeclarationWriter.cs
  src/Kiota.Builder/Writers/Swift/SwiftConventionService.cs
  src/Kiota.Builder/Writers/Swift/SwiftWriter.cs
Labels: generator

#1460 Add text formatter type to CLI
  CHANGELOG.md
  cli/commons/src/Microsoft.Kiota.Cli.Commons.Tests/IO/OutputFormatterFactoryTest.cs
  cli/commons/src/Microsoft.Kiota.Cli.Commons.Tests/IO/TextOutputFormatterTest.cs
  cli/commons/src/Microsoft.Kiota.Cli.Commons.Tests/Microsoft.Kiota.Cli.Commons.Tests.csproj
  cli/commons/src/Microsoft.Kiota.Cli.Commons.Tests/data/long_text_file.txt
  cli/commons/src/Microsoft.Kiota.Cli.Commons/IO/FormatterType.cs
  cli/commons/src/Microsoft.Kiota.Cli.Commons/IO/IOutputFormatter.cs
  cli/commons/src/Microsoft.Kiota.Cli.Commons/IO/JsonOutputFormatter.cs
  cli/commons/src/Microsoft.Kiota.Cli.Commons/IO/OutputFormatterFactory.cs
  cli/commons/src/Microsoft.Kiota.Cli.Commons/IO/OutputFormatterOptions.cs
  cli/commons/src/Microsoft.Kiota.Cli.Commons/IO/TableOutputFormatter.cs
  cli/commons/src/Microsoft.Kiota.Cli.Commons/IO/TextOutputFormatter.cs
  cli/commons/src/Microsoft.Kiota.Cli.Commons/Microsoft.Kiota.Cli.Commons.csproj
  src/Kiota.Builder/Writers/CSharp/CSharpConventionService.cs
  src/Kiota.Builder/Writers/Shell/ShellCodeMethodWriter.cs
  tests/Kiota.Builder.Tests/Writers/Shell/ShellCodeMethodWriterTests.cs
Labels: CLI

#1470 renames request parameters
  CHANGELOG.md
  src/Kiota.Builder/KiotaBuilder.cs
Labels: generator

#1467 - fixes #1443 a bug where the client would reset the base url if previously set
  CHANGELOG.md
  src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs
Labels: CSharp, TypeScript, Go, Java

#1476 Fix ambiguous types in dotnet
  CHANGELOG.md
  src/Kiota.Builder/Extensions/StringExtensions.cs
  src/Kiota.Builder/KiotaBuilder.cs
  src/Kiota.Builder/Refiners/CSharpRefiner.cs
  src/Kiota.Builder/Refiners/CSharpReservedNamesProvider.cs
  src/Kiota.Builder/Refiners/CSharpReservedTypesProvider.cs
  src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
  src/Kiota.Builder/Writers/CSharp/CSharpConventionService.cs
  src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
  tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Shell/ShellCodeMethodWriterTests.cs
Labels: CSharp
