Repository microsoft/kiota, pull requests merged in 2022-10, with the labels that each got.

#1869 adds show and info commands
  .vscode/launch.json
  CHANGELOG.md
  docs/using.md
  src/Kiota.Builder/Configuration/KiotaConfiguration.cs
  src/Kiota.Builder/Configuration/LanguagesInformation.cs
  src/Kiota.Builder/GenerationLanguage.cs
  src/Kiota.Builder/Kiota.Builder.csproj
  src/Kiota.Builder/KiotaBuilder.cs
  src/Kiota.Builder/KiotaSearcher.cs
  src/Kiota.Builder/LanguageInformation.cs
  src/Kiota.Builder/OpenApiExtensions/OpenApiKiotaExtension.cs
  src/Kiota.Builder/SearchProviders/OpenApiSpec/OpenApiSpecSeachProvider.cs
  src/kiota/BaseKiotaCommandHandler.cs
  src/kiota/Handlers/BaseKiotaCommandHandler.cs
  src/kiota/Handlers/KiotaDownloadCommandHandler.cs
  src/kiota/Handlers/KiotaGenerationCommandHandler.cs
  src/kiota/Handlers/KiotaInfoCommandHandler.cs
  src/kiota/Handlers/KiotaSeachBasedCommandHandler.cs
  src/kiota/Handlers/KiotaSearchCommandHandler.cs
  src/kiota/Handlers/KiotaShowCommandHandler.cs
  src/kiota/KiotaHost.cs
  src/kiota/appsettings.json
  src/kiota/kiota.csproj
  tests/Kiota.Builder.IntegrationTests/GenerateSample.cs
  tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
  tests/Kiota.Builder.Tests/OpenApiExtensions/OpenApiEnumValuesDescriptionExtensionTests.cs
  tests/Kiota.Builder.Tests/OpenApiExtensions/OpenApiKiotaExtensionTests.cs
  tests/Kiota.Builder.Tests/OpenApiExtensions/OpenApiPagingExtensionsTests.cs
Labels: enhancement, generator

#1878 feature/java no response handler
  CHANGELOG.md
  src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
  src/Kiota.Builder/Refiners/GoRefiner.cs
  src/Kiota.Builder/Refiners/JavaRefiner.cs
  src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
  tests/Kiota.Builder.Tests/Refiners/GoLanguageRefinerTests.cs
  tests/Kiota.Builder.Tests/Refiners/JavaLanguageRefinerTests.cs
  tests/Kiota.Builder.Tests/Writers/Java/CodeMethodWriterTests.cs
Labels: enhancement, Java

#1879 - fixes sonarcloud reported issues
  src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Python/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Ruby/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs
Labels: enhancement, generator

#1880 Php/refactor deserializer
  CHANGELOG.md
  src/Kiota.Builder/Writers/Php/CodeMethodWriter.cs
  tests/Kiota.Builder.Tests/Writers/Php/CodeMethodWriterTests.cs
Labels: PHP

#1885 - adds support for enum and collection of enum return types for Java
  CHANGELOG.md
  src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
Labels: Java

#1887 bugfix/java long discriminator
  CHANGELOG.md
  src/Kiota.Builder/CodeDOM/DiscriminatorInformation.cs
  src/Kiota.Builder/Refiners/JavaRefiner.cs
  src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
  tests/Kiota.Builder.Tests/Refiners/JavaLanguageRefinerTests.cs
  tests/Kiota.Builder.Tests/Writers/Java/CodeMethodWriterTests.cs
Labels: Java

#1792 Getting started with Python
  docs/get-started/python.md
  docs/get-started/reference-openapi.md
Labels: documentation

#1901 feature/commands enhancements
  CHANGELOG.md
  src/Kiota.Builder/Extensions/OpenApiUrlTreeNodeExtensions.cs
  src/Kiota.Builder/KiotaBuilder.cs
  src/Kiota.Builder/SearchProviders/APIsGuru/APIEntry.cs
  src/Kiota.Builder/SearchProviders/APIsGuru/APIsGuruSearchProvider.cs
  src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Php/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Python/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Ruby/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs
  src/kiota/Handlers/KiotaGenerationCommandHandler.cs
  src/kiota/Handlers/KiotaInfoCommandHandler.cs
  src/kiota/Handlers/KiotaShowCommandHandler.cs
  tests/Kiota.Builder.Tests/Extensions/OpenApiUrlTreeNodeExtensionsTests.cs
  tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Labels: generator

#1905 - fixes #1895 adds a colours scheme for console messages
  CHANGELOG.md
  src/kiota/Handlers/BaseKiotaCommandHandler.cs
  src/kiota/Handlers/KiotaDownloadCommandHandler.cs
  src/kiota/Handlers/KiotaGenerationCommandHandler.cs
  src/kiota/Handlers/KiotaInfoCommandHandler.cs
  src/kiota/Handlers/KiotaSeachBasedCommandHandler.cs
  src/kiota/Handlers/KiotaSearchCommandHandler.cs
Labels: generator

#1906 - fixes #1902 adds documentation for API Key authentication provider
  CHANGELOG.md
  README.md
  docs/extending/authentication.md
  docs/get-started/dotnet.md
  docs/get-started/go.md
  docs/get-started/java.md
  docs/get-started/typescript.md
Labels: CSharp, TypeScript, Go, Java

#1913 - fixes #1912 a bug where the info command would not format strings properly
  src/kiota/Handlers/KiotaInfoCommandHandler.cs
Labels: generator

#1915 Fix possible StackOverflow exception
  src/Kiota.Builder/Caching/DocumentCachingProvider.cs
  src/Kiota.Builder/Extensions/StringExtensions.cs
Labels: hacktoberfest-accepted

#1918 Async dispose and minor performance improvements.
  src/Kiota.Builder/CodeRenderers/CodeRenderer.cs
  src/Kiota.Builder/Extensions/OpenApiUrlTreeNodeExtensions.cs
  src/Kiota.Builder/Extensions/StringExtensions.cs
  src/Kiota.Builder/KiotaBuilder.cs
  src/Kiota.Builder/SearchProviders/APIsGuru/APIsGuruSearchProvider.cs
  src/Kiota.Builder/Writers/Shell/ShellCodeMethodWriter.cs
  src/kiota/Handlers/KiotaDownloadCommandHandler.cs
  tests/Kiota.Builder.Tests/Caching/DocumentCachingProviderTests.cs
  tests/Kiota.Builder.Tests/Extensions/StringExtensionsTests.cs
  tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
  tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Java/CodeMethodWriterTests.cs
Labels: hacktoberfest-accepted

#1916 - fixes an issue where CSharp defensive programing would use string.IsNullOrEmpty for collections parameters
  CHANGELOG.md
  src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
Labels: CSharp

#1922 app.kiota.dev
  .devcontainer/devcontainer.json
  .github/workflows/create-release.yml
  .vscode/extensions.json
  kiota.sln
  src/Kiota.Web/App.razor
  src/Kiota.Web/ComponentWithCancellationToken.cs
  src/Kiota.Web/Kiota.Web.csproj
  src/Kiota.Web/Pages/Generate.fr.resx
  src/Kiota.Web/Pages/Generate.razor
  src/Kiota.Web/Pages/Generate.resx
  src/Kiota.Web/Pages/Index.fr.resx
  src/Kiota.Web/Pages/Index.razor
  src/Kiota.Web/Pages/Index.resx
  src/Kiota.Web/Pages/Show.fr.resx
  src/Kiota.Web/Pages/Show.razor
  src/Kiota.Web/Pages/Show.resx
  src/Kiota.Web/Program.cs
  src/Kiota.Web/Properties/launchSettings.json
  src/Kiota.Web/Shared/MainLayout.razor
  src/Kiota.Web/Shared/MainLayout.razor.css
  src/Kiota.Web/Shared/NavMenu.fr.resx
  src/Kiota.Web/Shared/NavMenu.razor
  src/Kiota.Web/Shared/NavMenu.razor.css
  src/Kiota.Web/Shared/NavMenu.resx
  src/Kiota.Web/StringBuilderLogger.cs
  src/Kiota.Web/_Imports.razor
  src/Kiota.Web/wwwroot/appsettings.json
  src/Kiota.Web/wwwroot/css/app.css
  src/Kiota.Web/wwwroot/favicon.ico
  src/Kiota.Web/wwwroot/icon-192.png
  src/Kiota.Web/wwwroot/index.html
  src/Kiota.Web/wwwroot/kiota.webmanifest
  src/Kiota.Web/wwwroot/service-worker.js
  src/Kiota.Web/wwwroot/service-worker.published.js
Labels: generator

#1923 code linting for app.kiota.dev
  src/Kiota.Web/ComponentWithCancellationToken.cs
  src/Kiota.Web/Shared/MainLayout.razor
  src/Kiota.Web/Shared/MainLayout.razor.css
Labels: generator

#1928 - Fixes a bug where collections request bodies would not serialize single elements properly
  CHANGELOG.md
  abstractions/swift/Source/MicrosoftKiotaAbstractions/RequestInformation.swift
  src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs
  tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Java/CodeMethodWriterTests.cs
Labels: bug, CSharp

#1924 minor fixes for app.kiota.dev
  src/Kiota.Builder/KiotaBuilder.cs
  src/Kiota.Builder/SearchProviders/APIsGuru/APIsGuruSearchProvider.cs
  src/Kiota.Web/Pages/Generate.razor
  src/Kiota.Web/Pages/Index.fr.resx
  src/Kiota.Web/Pages/Index.razor
  src/Kiota.Web/Pages/Index.resx
  src/Kiota.Web/Pages/Show.fr.resx
  src/Kiota.Web/Pages/Show.razor
  src/Kiota.Web/Pages/Show.resx
  src/Kiota.Web/wwwroot/appsettings.json
  src/kiota/appsettings.json
Labels: generator
