Repository microsoft/kiota, pull requests merged in 2023-01, with the labels that each got.

#2114 bugfix/errors parent
  CHANGELOG.md
  src/Kiota.Builder/CodeDOM/CodeElement.cs
  src/Kiota.Builder/CodeDOM/CodeMethod.cs
  src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
  src/Kiota.Builder/Refiners/GoRefiner.cs
  src/Kiota.Builder/Refiners/JavaRefiner.cs
  src/Kiota.Builder/Refiners/PhpRefiner.cs
  src/Kiota.Builder/Refiners/PythonRefiner.cs
  src/Kiota.Builder/Refiners/RubyRefiner.cs
  src/Kiota.Builder/Refiners/SwiftRefiner.cs
  src/Kiota.Builder/Refiners/TypeScriptRefiner.cs
  tests/Kiota.Builder.Tests/CodeDOM/CodeClassTests.cs
  tests/Kiota.Builder.Tests/Refiners/GoLanguageRefinerTests.cs
  tests/Kiota.Builder.Tests/Refiners/JavaLanguageRefinerTests.cs
Labels: bug, generator

#1973 bugfix/m1
  .github/workflows/docker.yml
  CHANGELOG.md
  Dockerfile
  src/Kiota.Builder/KiotaBuilder.cs
  src/kiota/Handlers/BaseKiotaCommandHandler.cs
Labels: generator

#2115 - bumps version to 0.10.0 for release
  CHANGELOG.md
  src/Kiota.Builder/Kiota.Builder.csproj
  src/Kiota.Web/wwwroot/appsettings.json
  src/kiota/appsettings.json
  src/kiota/kiota.csproj
Labels: generator

#2123 feature/set base url
  CHANGELOG.md
  src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Ruby/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs
  tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Java/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Ruby/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/TypeScript/CodeMethodWriterTests.cs
Labels: generator

#2136 bugfix/deterministic description
  CHANGELOG.md
  src/Kiota.Builder/CodeRenderers/CodeRenderer.cs
  src/Kiota.Builder/CodeRenderers/TypeScriptCodeRenderer.cs
  src/Kiota.Builder/KiotaBuilder.cs
  src/Kiota.Builder/PathSegmenters/CommonPathSegmenter.cs
  src/Kiota.Builder/PathSegmenters/RubyPathSegmenter.cs
  src/Kiota.Builder/Writers/Ruby/CodeMethodWriter.cs
Labels: generator

#2126 feature/method rename
  CHANGELOG.md
  src/Kiota.Builder/KiotaBuilder.cs
  src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Ruby/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs
  tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Java/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Ruby/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/TypeScript/CodeMethodWriterTests.cs
Labels: generator

#2137 Follow up to set baseurl
  src/Kiota.Builder/Refiners/CSharpRefiner.cs
Labels: CSharp

#2138 - fixes a bug where CLI query/header/path parameters would not be deduplicated
  CHANGELOG.md
  src/Kiota.Builder/CodeDOM/CodeMethod.cs
  tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Labels: generator

#2148 - fixes a bug in ruby where file names or paths could be too long to be packaged
  CHANGELOG.md
  src/Kiota.Builder/CodeRenderers/CodeRenderer.cs
  src/Kiota.Builder/PathSegmenters/CommonPathSegmenter.cs
  src/Kiota.Builder/PathSegmenters/IPathSegmenter.cs
  src/Kiota.Builder/PathSegmenters/RubyPathSegmenter.cs
  src/Kiota.Builder/Refiners/RubyRefiner.cs
  src/Kiota.Builder/Writers/NamespaceClassNamesProvider.cs
  src/Kiota.Builder/Writers/RelativeImportManager.cs
  src/Kiota.Builder/Writers/Ruby/CodeClassDeclarationWriter.cs
  src/Kiota.Builder/Writers/Ruby/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/Ruby/CodeNamespaceWriter.cs
  src/Kiota.Builder/Writers/Ruby/RubyWriter.cs
  src/Kiota.Builder/Writers/TypeScript/CodeNameSpaceWriter.cs
  tests/Kiota.Builder.Tests/Refiners/RubyLanguageRefinerTests.cs
  tests/Kiota.Builder.Tests/Writers/Ruby/CodeClassDeclarationWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Ruby/CodeNamespaceWriterTests.cs
Labels: Ruby

#2156 Task/remove response handler param
  CHANGELOG.md
  src/Kiota.Builder/Refiners/PythonRefiner.cs
  src/Kiota.Builder/Writers/Python/CodeMethodWriter.cs
Labels: enhancement

#2178 bugfix/NRT composed
  CHANGELOG.md
  src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
  src/Kiota.Builder/Writers/CSharp/CSharpConventionService.cs
  src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
  src/Kiota.Builder/Writers/CSharp/CodePropertyWriter.cs
  src/Kiota.Generated/KiotaGenerated.csproj
  src/Kiota.Web/wwwroot/appsettings.json
  src/kiota/Handlers/BaseKiotaCommandHandler.cs
  src/kiota/appsettings.json
  tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs
Labels: CSharp

#2176 PHP - Remove response handler parameter from request executor methods
  CHANGELOG.md
  src/Kiota.Builder/Refiners/PhpRefiner.cs
  src/Kiota.Builder/Writers/Php/CodeMethodWriter.cs
  tests/Kiota.Builder.Tests/Writers/Php/CodeMethodWriterTests.cs
Labels: PHP

#2182 bugfix/dvr all
  CHANGELOG.md
  docs/using.md
  src/Kiota.Builder/KiotaBuilder.cs
  src/Kiota.Builder/Validation/ValidationRuleSetExtensions.cs
  src/kiota/Handlers/KiotaGenerationCommandHandler.cs
Labels: bug
