Repository microsoft/kiota, pull requests merged in 2023-02, with the labels that each got.

#2208 - adds missing dependencies in getting started docs
  docs/get-started/go.md
  docs/get-started/java.md
  docs/get-started/typescript.md
Labels: documentation

#2214 - attempt at reducing the number of icons being produced
  src/Kiota.Web/Kiota.Web.csproj
  src/Kiota.Web/Program.cs
Labels: generator

#2237 - adds documentation regarding errors handling
  docs/extending/errors.md
Labels: documentation

#2273 - fixes a bug where ruby long namespace name would make packaging fail
  CHANGELOG.md
  src/Kiota.Builder/CodeDOM/CodeBlock.cs
  src/Kiota.Builder/PathSegmenters/RubyPathSegmenter.cs
  src/Kiota.Builder/Refiners/RubyRefiner.cs
  tests/Kiota.Builder.Tests/Refiners/RubyLanguageRefinerTests.cs
Labels: Ruby

#2272 - bumps version to 0.11.0 for release
  CHANGELOG.md
  src/Kiota.Builder/Kiota.Builder.csproj
  src/Kiota.Web/wwwroot/appsettings.json
  src/kiota/appsettings.json
  src/kiota/kiota.csproj
Labels: generator

#2275 - fixes a bug where Go collections would try to use variadic parameters where not supported
  CHANGELOG.md
  src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
Labels: Go

#2276 - adds precisions regarding the release schedule
  docs/support.md
Labels: documentation

#2282 Python/bugfix exception fields
  CHANGELOG.md
  src/Kiota.Builder/Refiners/PythonExceptionsReservedNamesProvider.cs
  src/Kiota.Builder/Refiners/PythonRefiner.cs
  tests/Kiota.Builder.Tests/Refiners/PythonLanguageRefinerTests.cs
Labels: bug

#2283 - fixes a bug in ruby where modules would be undeclared
  CHANGELOG.md
  src/Kiota.Builder/Writers/Ruby/CodeBlockEndWriter.cs
  src/Kiota.Builder/Writers/Ruby/CodeClassDeclarationWriter.cs
  src/Kiota.Builder/Writers/Ruby/CodeEnumWriter.cs
  src/Kiota.Builder/Writers/Ruby/CodeNamespaceWriter.cs
  src/Kiota.Builder/Writers/Ruby/RubyConventionService.cs
  tests/Kiota.Builder.Tests/Writers/Ruby/CodeNamespaceWriterTests.cs
Labels: Ruby

#2280 PHP - Add constructor to query parameter and request configuration classes
  CHANGELOG.md
  src/Kiota.Builder/Refiners/PhpRefiner.cs
  src/Kiota.Builder/Writers/Php/CodeMethodWriter.cs
  tests/Kiota.Builder.Tests/Writers/Php/CodeMethodWriterTests.cs
Labels: PHP

#2313 PHP - Make getAdditionalData return type nullable
  CHANGELOG.md
  src/Kiota.Builder/Refiners/PhpRefiner.cs
  tests/Kiota.Builder.Tests/Writers/Php/CodeMethodWriterTests.cs
  tests/Kiota.Builder.Tests/Writers/Php/CodePropertyWriterTests.cs
Labels: PHP

#2314 Fixes inconsistent request builder generation
  CHANGELOG.md
  src/Kiota.Builder/KiotaBuilder.cs
  tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Labels: generator

#2323 PHP - Change request options type in PHPDoc from map to array
  CHANGELOG.md
  src/Kiota.Builder/Writers/Php/CodePropertyWriter.cs
  tests/Kiota.Builder.Tests/Writers/Php/CodePropertyWriterTests.cs
Labels: PHP

#2328 - adds restoration of the kiota-lock when the generation fails with clean output
  CHANGELOG.md
  src/Kiota.Builder/Caching/DocumentCachingProvider.cs
  src/Kiota.Builder/KiotaBuilder.cs
  src/Kiota.Builder/Lock/ILockManagementService.cs
  src/Kiota.Builder/Lock/LockManagementService.cs
Labels: generator
